
GET http://localhost:8080/api/admin/users
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJtYXJpdXMuYWRtaW5AZXhhbXBsZS5jb20iLCJpZCI6MywiZmlyc3ROYW1lIjoiTWFyaXVzIiwibGFzdE5hbWUiOiJWb24gTWF5ZW5idXJnIiwicm9sZXMiOlsiQURNSU4iXSwiaWF0IjoxNzgwMjYwMDU2LCJleHAiOjE3ODAzNDY0NTZ9.unQmwbPsgoVNVKx4SlUu2VHwyVmkLhhShPmK4nctuTyavEyVuatnetli7-lEXdOqGNpdcJlFJ6LMX_K3tvHz1g
