INSERT INTO users (id, email, password, first_name, last_name, profile_image_url, consent_rgpd)
VALUES
    (1,'hash.test@email.com','$2a$10$Wwz0XduZAMxzqlyFjeawneZM/ein81KWR1s24rE2RqwZAhH/EAyc2','hash','test','/uploads/members/default-profile.png',true),
    (2,'philippe.partner@example.com','$2a$10$Wwz0XduZAMxzqlyFjeawneZM/ein81KWR1s24rE2RqwZAhH/EAyc2','Philippe','Laurent','/uploads/partners/default-logo.png',true),
    (3,'marius.admin@example.com','$2a$10$Wwz0XduZAMxzqlyFjeawneZM/ein81KWR1s24rE2RqwZAhH/EAyc2','Marius','Von Mayenburg','/uploads/members/default-profile.png',true),
    (4,'olivier.member@example.com','$2a$10$Wwz0XduZAMxzqlyFjeawneZM/ein81KWR1s24rE2RqwZAhH/EAyc2','Olivier','Boudon','/uploads/members/default-profile.png',true),
    (5,'annemarie.loop@example.com','$2a$10$Wwz0XduZAMxzqlyFjeawneZM/ein81KWR1s24rE2RqwZAhH/EAyc2','Anne Marie','Loop','/uploads/members/default-profile.png',true),
    (6,'pietro.varasso@example.com','$2a$10$Wwz0XduZAMxzqlyFjeawneZM/ein81KWR1s24rE2RqwZAhH/EAyc2','Pietro','Varasso','/uploads/members/default-profile.png',true),
    (7,'laurent.caron@example.com','$2a$10$Wwz0XduZAMxzqlyFjeawneZM/ein81KWR1s24rE2RqwZAhH/EAyc2','Laurent','Caron','/uploads/members/default-profile.png',true),
    (8,'elena.perez@example.com','$2a$10$Wwz0XduZAMxzqlyFjeawneZM/ein81KWR1s24rE2RqwZAhH/EAyc2','Élena','Perez','/uploads/members/default-profile.png',true),
    (9,'guillaume.alexandre@example.com','$2a$10$Wwz0XduZAMxzqlyFjeawneZM/ein81KWR1s24rE2RqwZAhH/EAyc2','Guillaume','Alexandre','/uploads/members/default-profile.png',true),
    (10,'claude.semal@example.com','$2a$10$Wwz0XduZAMxzqlyFjeawneZM/ein81KWR1s24rE2RqwZAhH/EAyc2','Claude','Semal','/uploads/members/default-profile.png',true),

    (11,'laurence.warin@example.com','$2a$10$Wwz0XduZAMxzqlyFjeawneZM/ein81KWR1s24rE2RqwZAhH/EAyc2','Laurence','Warin','/uploads/members/default-profile.png',true),
    (12,'pierre.wayburn@example.com','$2a$10$Wwz0XduZAMxzqlyFjeawneZM/ein81KWR1s24rE2RqwZAhH/EAyc2','Pierre','Wayburn','/uploads/members/default-profile.png',true),
    (13,'gwendoline.gauthier@example.com','$2a$10$Wwz0XduZAMxzqlyFjeawneZM/ein81KWR1s24rE2RqwZAhH/EAyc2','Gwendoline','Gauthier','/uploads/members/default-profile.png',true),
    (14,'jacques.brel@example.com','$2a$10$Wwz0XduZAMxzqlyFjeawneZM/ein81KWR1s24rE2RqwZAhH/EAyc2','Jacques','Brel','/uploads/members/default-profile.png',true),
    (15,'salvatore.adamo@example.com','$2a$10$Wwz0XduZAMxzqlyFjeawneZM/ein81KWR1s24rE2RqwZAhH/EAyc2','Salvatore','Adamo','/uploads/members/default-profile.png',true),
    (16,'stromae.cowboy@example.com','$2a$10$Wwz0XduZAMxzqlyFjeawneZM/ein81KWR1s24rE2RqwZAhH/EAyc2','Stromae','Cowboy','/uploads/members/default-profile.png',true),
    (17,'angele.vanlaeken@example.com','$2a$10$Wwz0XduZAMxzqlyFjeawneZM/ein81KWR1s24rE2RqwZAhH/EAyc2','Angèle','Van Laeken','/uploads/members/default-profile.png',true),
    (18,'arno.hintjens@example.com','$2a$10$Wwz0XduZAMxzqlyFjeawneZM/ein81KWR1s24rE2RqwZAhH/EAyc2','Arno','Hintjens','/uploads/members/default-profile.png',true),
    (19,'alex.callier@example.com','$2a$10$Wwz0XduZAMxzqlyFjeawneZM/ein81KWR1s24rE2RqwZAhH/EAyc2','Alex','Callier','/uploads/members/default-profile.png',true),
    (20,'wouter.debacker@example.com','$2a$10$Wwz0XduZAMxzqlyFjeawneZM/ein81KWR1s24rE2RqwZAhH/EAyc2','Wouter','De Backer','/uploads/members/default-profile.png',true),

    (21,'jean.dupont@example.com','$2a$10$Wwz0XduZAMxzqlyFjeawneZM/ein81KWR1s24rE2RqwZAhH/EAyc2','Jean','Dupont','/uploads/members/default-profile.png',true),
    (22,'marie.martin@example.com','$2a$10$Wwz0XduZAMxzqlyFjeawneZM/ein81KWR1s24rE2RqwZAhH/EAyc2','Marie','Martin','/uploads/members/default-profile.png',true),
    (23,'paul.moreau@example.com','$2a$10$Wwz0XduZAMxzqlyFjeawneZM/ein81KWR1s24rE2RqwZAhH/EAyc2','Paul','Moreau','/uploads/members/default-profile.png',true),
    (24,'sophie.lefevre@example.com','$2a$10$Wwz0XduZAMxzqlyFjeawneZM/ein81KWR1s24rE2RqwZAhH/EAyc2','Sophie','Lefèvre','/uploads/members/default-profile.png',true),
    (25,'antoine.petit@example.com','$2a$10$Wwz0XduZAMxzqlyFjeawneZM/ein81KWR1s24rE2RqwZAhH/EAyc2','Antoine','Petit','/uploads/members/default-profile.png',true),
    (26,'claire.laurent@example.com','$2a$10$Wwz0XduZAMxzqlyFjeawneZM/ein81KWR1s24rE2RqwZAhH/EAyc2','Claire','Laurent','/uploads/members/default-profile.png',true),
    (27,'nicolas.roche@example.com','$2a$10$Wwz0XduZAMxzqlyFjeawneZM/ein81KWR1s24rE2RqwZAhH/EAyc2','Nicolas','Roche','/uploads/members/default-profile.png',true),
    (28,'emilie.dubois@example.com','$2a$10$Wwz0XduZAMxzqlyFjeawneZM/ein81KWR1s24rE2RqwZAhH/EAyc2','Émilie','Dubois','/uploads/members/default-profile.png',true),
    (29,'guillaume.durand@example.com','$2a$10$Wwz0XduZAMxzqlyFjeawneZM/ein81KWR1s24rE2RqwZAhH/EAyc2','Guillaume','Durand','/uploads/members/default-profile.png',true),
    (30,'camille.leroy@example.com','$2a$10$Wwz0XduZAMxzqlyFjeawneZM/ein81KWR1s24rE2RqwZAhH/EAyc2','Camille','Leroy','/uploads/members/default-profile.png',true),

    (31,'jan.devries@example.com','$2a$10$Wwz0XduZAMxzqlyFjeawneZM/ein81KWR1s24rE2RqwZAhH/EAyc2','Jan','De Vries','/uploads/members/default-profile.png',true),
    (32,'piet.janssen@example.com','$2a$10$Wwz0XduZAMxzqlyFjeawneZM/ein81KWR1s24rE2RqwZAhH/EAyc2','Piet','Janssen','/uploads/members/default-profile.png',true),
    (33,'karel.debruin@example.com','$2a$10$Wwz0XduZAMxzqlyFjeawneZM/ein81KWR1s24rE2RqwZAhH/EAyc2','Karel','De Bruin','/uploads/members/default-profile.png',true),
    (34,'femke.visser@example.com','$2a$10$Wwz0XduZAMxzqlyFjeawneZM/ein81KWR1s24rE2RqwZAhH/EAyc2','Femke','Visser','/uploads/members/default-profile.png',true),
    (35,'bram.smit@example.com','$2a$10$Wwz0XduZAMxzqlyFjeawneZM/ein81KWR1s24rE2RqwZAhH/EAyc2','Bram','Smit','/uploads/members/default-profile.png',true),
    (36,'sanne.bakker@example.com','$2a$10$Wwz0XduZAMxzqlyFjeawneZM/ein81KWR1s24rE2RqwZAhH/EAyc2','Sanne','Bakker','/uploads/members/default-profile.png',true),
    (37,'tom.verhoeven@example.com','$2a$10$Wwz0XduZAMxzqlyFjeawneZM/ein81KWR1s24rE2RqwZAhH/EAyc2','Tom','Verhoeven','/uploads/members/default-profile.png',true),
    (38,'lotte.dewit@example.com','$2a$10$Wwz0XduZAMxzqlyFjeawneZM/ein81KWR1s24rE2RqwZAhH/EAyc2','Lotte','De Wit','/uploads/members/default-profile.png',true),
    (39,'daan.vandijk@example.com','$2a$10$Wwz0XduZAMxzqlyFjeawneZM/ein81KWR1s24rE2RqwZAhH/EAyc2','Daan','Van Dijk','/uploads/members/default-profile.png',true),
    (40,'emma.delange@example.com','$2a$10$Wwz0XduZAMxzqlyFjeawneZM/ein81KWR1s24rE2RqwZAhH/EAyc2','Emma','De Lange','/uploads/members/default-profile.png',true),

    (41,'michael.smith@example.com','$2a$10$Wwz0XduZAMxzqlyFjeawneZM/ein81KWR1s24rE2RqwZAhH/EAyc2','Michael','Smith','/uploads/members/default-profile.png',true),
    (42,'jennifer.johnson@example.com','$2a$10$Wwz0XduZAMxzqlyFjeawneZM/ein81KWR1s24rE2RqwZAhH/EAyc2','Jennifer','Johnson','/uploads/members/default-profile.png',true),
    (43,'william.brown@example.com','$2a$10$Wwz0XduZAMxzqlyFjeawneZM/ein81KWR1s24rE2RqwZAhH/EAyc2','William','Brown','/uploads/members/default-profile.png',true),
    (44,'elizabeth.davis@example.com','$2a$10$Wwz0XduZAMxzqlyFjeawneZM/ein81KWR1s24rE2RqwZAhH/EAyc2','Elizabeth','Davis','/uploads/members/default-profile.png',true),
    (45,'james.wilson@example.com','$2a$10$Wwz0XduZAMxzqlyFjeawneZM/ein81KWR1s24rE2RqwZAhH/EAyc2','James','Wilson','/uploads/members/default-profile.png',true),
    (46,'mary.taylor@example.com','$2a$10$Wwz0XduZAMxzqlyFjeawneZM/ein81KWR1s24rE2RqwZAhH/EAyc2','Mary','Taylor','/uploads/members/default-profile.png',true),
    (47,'robert.anderson@example.com','$2a$10$Wwz0XduZAMxzqlyFjeawneZM/ein81KWR1s24rE2RqwZAhH/EAyc2','Robert','Anderson','/uploads/members/default-profile.png',true),
    (48,'patricia.thomas@example.com','$2a$10$Wwz0XduZAMxzqlyFjeawneZM/ein81KWR1s24rE2RqwZAhH/EAyc2','Patricia','Thomas','/uploads/members/default-profile.png',true),
    (49,'david.jackson@example.com','$2a$10$Wwz0XduZAMxzqlyFjeawneZM/ein81KWR1s24rE2RqwZAhH/EAyc2','David','Jackson','/uploads/members/default-profile.png',true),
    (50,'linda.white@example.com','$2a$10$Wwz0XduZAMxzqlyFjeawneZM/ein81KWR1s24rE2RqwZAhH/EAyc2','Linda','White','/uploads/members/default-profile.png',true),

    (51,'martin.robinson@example.com','$2a$10$Wwz0XduZAMxzqlyFjeawneZM/ein81KWR1s24rE2RqwZAhH/EAyc2','Martin','Robinson','/uploads/members/default-profile.png',true),
    (52,'sophie.edwards@example.com','$2a$10$Wwz0XduZAMxzqlyFjeawneZM/ein81KWR1s24rE2RqwZAhH/EAyc2','Sophie','Edwards','/uploads/members/default-profile.png',true),
    (53,'alexandre.bernard@example.com','$2a$10$Wwz0XduZAMxzqlyFjeawneZM/ein81KWR1s24rE2RqwZAhH/EAyc2','Alexandre','Bernard','/uploads/members/default-profile.png',true),
    (54,'chloe.fontaine@example.com','$2a$10$Wwz0XduZAMxzqlyFjeawneZM/ein81KWR1s24rE2RqwZAhH/EAyc2','Chloé','Fontaine','/uploads/members/default-profile.png',true),
    (55,'laurent.marchand@example.com','$2a$10$Wwz0XduZAMxzqlyFjeawneZM/ein81KWR1s24rE2RqwZAhH/EAyc2','Laurent','Marchand','/uploads/members/default-profile.png',true),
    (56,'isabelle.garnier@example.com','$2a$10$Wwz0XduZAMxzqlyFjeawneZM/ein81KWR1s24rE2RqwZAhH/EAyc2','Isabelle','Garnier','/uploads/members/default-profile.png',true),
    (57,'sebastien.girard@example.com','$2a$10$Wwz0XduZAMxzqlyFjeawneZM/ein81KWR1s24rE2RqwZAhH/EAyc2','Sébastien','Girard','/uploads/members/default-profile.png',true),
    (58,'manon.petitjean@example.com','$2a$10$Wwz0XduZAMxzqlyFjeawneZM/ein81KWR1s24rE2RqwZAhH/EAyc2','Manon','Petitjean','/uploads/members/default-profile.png',true),
    (59,'olivier.dupuis@example.com','$2a$10$Wwz0XduZAMxzqlyFjeawneZM/ein81KWR1s24rE2RqwZAhH/EAyc2','Olivier','Dupuis','/uploads/members/default-profile.png',true),
    (60,'juliette.renault@example.com','$2a$10$Wwz0XduZAMxzqlyFjeawneZM/ein81KWR1s24rE2RqwZAhH/EAyc2','Juliette','Renault','/uploads/members/default-profile.png',true),

    (61,'hugo.rousseau@example.com','$2a$10$Wwz0XduZAMxzqlyFjeawneZM/ein81KWR1s24rE2RqwZAhH/EAyc2','Hugo','Rousseau','/uploads/members/default-profile.png',true),
    (62,'elise.fontaine@example.com','$2a$10$Wwz0XduZAMxzqlyFjeawneZM/ein81KWR1s24rE2RqwZAhH/EAyc2','Élise','Fontaine','/uploads/members/default-profile.png',true),
    (63,'pascal.martin@example.com','$2a$10$Wwz0XduZAMxzqlyFjeawneZM/ein81KWR1s24rE2RqwZAhH/EAyc2','Pascal','Martin','/uploads/members/default-profile.png',true),
    (64,'claire.fournier@example.com','$2a$10$Wwz0XduZAMxzqlyFjeawneZM/ein81KWR1s24rE2RqwZAhH/EAyc2','Claire','Fournier','/uploads/members/default-profile.png',true),
    (65,'laurent.morel@example.com','$2a$10$Wwz0XduZAMxzqlyFjeawneZM/ein81KWR1s24rE2RqwZAhH/EAyc2','Laurent','Morel','/uploads/members/default-profile.png',true),
    (66,'amandine.caron@example.com','$2a$10$Wwz0XduZAMxzqlyFjeawneZM/ein81KWR1s24rE2RqwZAhH/EAyc2','Amandine','Caron','/uploads/members/default-profile.png',true),
    (67,'vincent.lefevre@example.com','$2a$10$Wwz0XduZAMxzqlyFjeawneZM/ein81KWR1s24rE2RqwZAhH/EAyc2','Vincent','Lefèvre','/uploads/members/default-profile.png',true),
    (68,'audrey.mercier@example.com','$2a$10$Wwz0XduZAMxzqlyFjeawneZM/ein81KWR1s24rE2RqwZAhH/EAyc2','Audrey','Mercier','/uploads/members/default-profile.png',true),
    (69,'romain.gauthier@example.com','$2a$10$Wwz0XduZAMxzqlyFjeawneZM/ein81KWR1s24rE2RqwZAhH/EAyc2','Romain','Gauthier','/uploads/members/default-profile.png',true),
    (70,'marine.dupont@example.com','$2a$10$Wwz0XduZAMxzqlyFjeawneZM/ein81KWR1s24rE2RqwZAhH/EAyc2','Marine','Dupont','/uploads/members/default-profile.png',true),

    (71,'dirk.vermeer@example.com','$2a$10$Wwz0XduZAMxzqlyFjeawneZM/ein81KWR1s24rE2RqwZAhH/EAyc2','Dirk','Vermeer','/uploads/members/default-profile.png',true),
    (72,'anke.vandenberg@example.com','$2a$10$Wwz0XduZAMxzqlyFjeawneZM/ein81KWR1s24rE2RqwZAhH/EAyc2','Anke','Van den Berg','/uploads/members/default-profile.png',true),
    (73,'tim.dejong@example.com','$2a$10$Wwz0XduZAMxzqlyFjeawneZM/ein81KWR1s24rE2RqwZAhH/EAyc2','Tim','De Jong','/uploads/members/default-profile.png',true),
    (74,'eva.degraaf@example.com','$2a$10$Wwz0XduZAMxzqlyFjeawneZM/ein81KWR1s24rE2RqwZAhH/EAyc2','Eva','De Graaf','/uploads/members/default-profile.png',true),
    (75,'joost.deruiter@example.com','$2a$10$Wwz0XduZAMxzqlyFjeawneZM/ein81KWR1s24rE2RqwZAhH/EAyc2','Joost','De Ruiter','/uploads/members/default-profile.png',true),
    (76,'lisa.veenstra@example.com','$2a$10$Wwz0XduZAMxzqlyFjeawneZM/ein81KWR1s24rE2RqwZAhH/EAyc2','Lisa','Veenstra','/uploads/members/default-profile.png',true),
    (77,'bas.mulder@example.com','$2a$10$Wwz0XduZAMxzqlyFjeawneZM/ein81KWR1s24rE2RqwZAhH/EAyc2','Bas','Mulder','/uploads/members/default-profile.png',true),
    (78,'marieke.deklerk@example.com','$2a$10$Wwz0XduZAMxzqlyFjeawneZM/ein81KWR1s24rE2RqwZAhH/EAyc2','Marieke','De Klerk','/uploads/members/default-profile.png',true),
    (79,'rik.bos@example.com','$2a$10$Wwz0XduZAMxzqlyFjeawneZM/ein81KWR1s24rE2RqwZAhH/EAyc2','Rik','Bos','/uploads/members/default-profile.png',true),
    (80,'sander.devries@example.com','$2a$10$Wwz0XduZAMxzqlyFjeawneZM/ein81KWR1s24rE2RqwZAhH/EAyc2','Sander','De Vries','/uploads/members/default-profile.png',true),

    (81,'oliver.jones@example.com','$2a$10$Wwz0XduZAMxzqlyFjeawneZM/ein81KWR1s24rE2RqwZAhH/EAyc2','Oliver','Jones','/uploads/members/default-profile.png',true),
    (82,'amelia.harris@example.com','$2a$10$Wwz0XduZAMxzqlyFjeawneZM/ein81KWR1s24rE2RqwZAhH/EAyc2','Amelia','Harris','/uploads/members/default-profile.png',true),
    (83,'benjamin.thompson@example.com','$2a$10$Wwz0XduZAMxzqlyFjeawneZM/ein81KWR1s24rE2RqwZAhH/EAyc2','Benjamin','Thompson','/uploads/members/default-profile.png',true),
    (84,'charlotte.martin@example.com','$2a$10$Wwz0XduZAMxzqlyFjeawneZM/ein81KWR1s24rE2RqwZAhH/EAyc2','Charlotte','Martin','/uploads/members/default-profile.png',true),
    (85,'henry.walker@example.com','$2a$10$Wwz0XduZAMxzqlyFjeawneZM/ein81KWR1s24rE2RqwZAhH/EAyc2','Henry','Walker','/uploads/members/default-profile.png',true),
    (86,'grace.robinson@example.com','$2a$10$Wwz0XduZAMxzqlyFjeawneZM/ein81KWR1s24rE2RqwZAhH/EAyc2','Grace','Robinson','/uploads/members/default-profile.png',true),
    (87,'samuel.lewis@example.com','$2a$10$Wwz0XduZAMxzqlyFjeawneZM/ein81KWR1s24rE2RqwZAhH/EAyc2','Samuel','Lewis','/uploads/members/default-profile.png',true),
    (88,'victoria.clark@example.com','$2a$10$Wwz0XduZAMxzqlyFjeawneZM/ein81KWR1s24rE2RqwZAhH/EAyc2','Victoria','Clark','/uploads/members/default-profile.png',true),
    (89,'jack.hall@example.com','$2a$10$Wwz0XduZAMxzqlyFjeawneZM/ein81KWR1s24rE2RqwZAhH/EAyc2','Jack','Hall','/uploads/members/default-profile.png',true),
    (90,'emily.allen@example.com','$2a$10$Wwz0XduZAMxzqlyFjeawneZM/ein81KWR1s24rE2RqwZAhH/EAyc2','Emily','Allen','/uploads/members/default-profile.png',true),

    (91,'mathieu.bernard@example.com','$2a$10$Wwz0XduZAMxzqlyFjeawneZM/ein81KWR1s24rE2RqwZAhH/EAyc2','Mathieu','Bernard','/uploads/members/default-profile.png',true),
    (92,'fiona.gallagher@example.com','$2a$10$Wwz0XduZAMxzqlyFjeawneZM/ein81KWR1s24rE2RqwZAhH/EAyc2','Fiona','Gallagher','/uploads/members/default-profile.png',true),
    (93,'sophie.rousseau@example.com','$2a$10$Wwz0XduZAMxzqlyFjeawneZM/ein81KWR1s24rE2RqwZAhH/EAyc2','Sophie','Rousseau','/uploads/members/default-profile.png',true),
    (94,'leo.gibson@example.com','$2a$10$Wwz0XduZAMxzqlyFjeawneZM/ein81KWR1s24rE2RqwZAhH/EAyc2','Leo','Gibson','/uploads/members/default-profile.png',true),
    (95,'emma.cooper@example.com','$2a$10$Wwz0XduZAMxzqlyFjeawneZM/ein81KWR1s24rE2RqwZAhH/EAyc2','Emma','Cooper','/uploads/members/default-profile.png',true),
    (96,'liam.carter@example.com','$2a$10$Wwz0XduZAMxzqlyFjeawneZM/ein81KWR1s24rE2RqwZAhH/EAyc2','Liam','Carter','/uploads/members/default-profile.png',true),
    (97,'zoe.marshall@example.com','$2a$10$Wwz0XduZAMxzqlyFjeawneZM/ein81KWR1s24rE2RqwZAhH/EAyc2','Zoe','Marshall','/uploads/members/default-profile.png',true),
    (98,'mason.scott@example.com','$2a$10$Wwz0XduZAMxzqlyFjeawneZM/ein81KWR1s24rE2RqwZAhH/EAyc2','Mason','Scott','/uploads/members/default-profile.png',true),
    (99,'ava.peterson@example.com','$2a$10$Wwz0XduZAMxzqlyFjeawneZM/ein81KWR1s24rE2RqwZAhH/EAyc2','Ava','Peterson','/uploads/members/default-profile.png',true),
    (100,'oliver.wright@example.com','$2a$10$Wwz0XduZAMxzqlyFjeawneZM/ein81KWR1s24rE2RqwZAhH/EAyc2','Oliver','Wright','/uploads/members/default-profile.png',true);