INSERT INTO users (id, email, password, first_name, last_name, consent_rgpd)
VALUES
    (1,'daniel.marcelin@example.com','$2a$10$abcdefghijklmnopqrstuv','Daniel','Marcelin',true),
    (2,'philippe.laurent@example.com','$2a$10$abcdefghijklmnopqrstuv','Philippe','Laurent',true),
    (3,'marius.vonmayenburg@example.com','$2a$10$abcdefghijklmnopqrstuv','Marius','Von Mayenburg',true),
    (4,'olivier.boudon@example.com','$2a$10$abcdefghijklmnopqrstuv','Olivier','Boudon',true),
    (5,'annemarie.loop@example.com','$2a$10$abcdefghijklmnopqrstuv','Anne Marie','Loop',true),
    (6,'pietro.varasso@example.com','$2a$10$abcdefghijklmnopqrstuv','Pietro','Varasso',true),
    (7,'laurent.caron@example.com','$2a$10$abcdefghijklmnopqrstuv','Laurent','Caron',true),
    (8,'elena.perez@example.com','$2a$10$abcdefghijklmnopqrstuv','Élena','Perez',true),
    (9,'guillaume.alexandre@example.com','$2a$10$abcdefghijklmnopqrstuv','Guillaume','Alexandre',true),
    (10,'claude.semal@example.com','$2a$10$abcdefghijklmnopqrstuv','Claude','Semal',true),
    (11,'laurence.warin@example.com','$2a$10$abcdefghijklmnopqrstuv','Laurence','Warin',true),
    (12,'pierre.wayburn@example.com','$2a$10$abcdefghijklmnopqrstuv','Pierre','Wayburn',true),
    (13,'gwendoline.gauthier@example.com','$2a$10$abcdefghijklmnopqrstuv','Gwendoline','Gauthier',true),
    (14,'jacques.brel@example.com','$2a$10$abcdefghijklmnopqrstuv','Jacques','Brel',true),
    (15,'salvatore.adamo@example.com','$2a$10$abcdefghijklmnopqrstuv','Salvatore','Adamo',true),
    (16,'stromae.cowboy@example.com','$2a$10$abcdefghijklmnopqrstuv','Stromae','Cowboy',true),
    (17,'angele.vanlaeken@example.com','$2a$10$abcdefghijklmnopqrstuv','Angèle','Van Laeken',true),
    (18,'arno.hintjens@example.com','$2a$10$abcdefghijklmnopqrstuv','Arno','Hintjens',true),
    (19,'alex.callier@example.com','$2a$10$abcdefghijklmnopqrstuv','Alex','Callier',true),
    (20,'wouter.debacker@example.com','$2a$10$abcdefghijklmnopqrstuv','Wouter','De Backer',true),

    (21,'jean.dupont@example.com','$2a$10$abcdefghijklmnopqrstuv','Jean','Dupont',true),
    (22,'marie.martin@example.com','$2a$10$abcdefghijklmnopqrstuv','Marie','Martin',true),
    (23,'paul.moreau@example.com','$2a$10$abcdefghijklmnopqrstuv','Paul','Moreau',true),
    (24,'sophie.lefevre@example.com','$2a$10$abcdefghijklmnopqrstuv','Sophie','Lefèvre',true),
    (25,'antoine.petit@example.com','$2a$10$abcdefghijklmnopqrstuv','Antoine','Petit',true),
    (26,'claire.laurent@example.com','$2a$10$abcdefghijklmnopqrstuv','Claire','Laurent',true),
    (27,'nicolas.roche@example.com','$2a$10$abcdefghijklmnopqrstuv','Nicolas','Roche',true),
    (28,'emilie.dubois@example.com','$2a$10$abcdefghijklmnopqrstuv','Émilie','Dubois',true),
    (29,'guillaume.durand@example.com','$2a$10$abcdefghijklmnopqrstuv','Guillaume','Durand',true),
    (30,'camille.leroy@example.com','$2a$10$abcdefghijklmnopqrstuv','Camille','Leroy',true),

    (31,'jan.devries@example.com','$2a$10$abcdefghijklmnopqrstuv','Jan','De Vries',true),
    (32,'piet.janssen@example.com','$2a$10$abcdefghijklmnopqrstuv','Piet','Janssen',true),
    (33,'karel.debruin@example.com','$2a$10$abcdefghijklmnopqrstuv','Karel','De Bruin',true),
    (34,'femke.visser@example.com','$2a$10$abcdefghijklmnopqrstuv','Femke','Visser',true),
    (35,'bram.smit@example.com','$2a$10$abcdefghijklmnopqrstuv','Bram','Smit',true),
    (36,'sanne.bakker@example.com','$2a$10$abcdefghijklmnopqrstuv','Sanne','Bakker',true),
    (37,'tom.verhoeven@example.com','$2a$10$abcdefghijklmnopqrstuv','Tom','Verhoeven',true),
    (38,'lotte.dewit@example.com','$2a$10$abcdefghijklmnopqrstuv','Lotte','De Wit',true),
    (39,'daan.vandijk@example.com','$2a$10$abcdefghijklmnopqrstuv','Daan','Van Dijk',true),
    (40,'emma.delange@example.com','$2a$10$abcdefghijklmnopqrstuv','Emma','De Lange',true),

    (41,'michael.smith@example.com','$2a$10$abcdefghijklmnopqrstuv','Michael','Smith',true),
    (42,'jennifer.johnson@example.com','$2a$10$abcdefghijklmnopqrstuv','Jennifer','Johnson',true),
    (43,'william.brown@example.com','$2a$10$abcdefghijklmnopqrstuv','William','Brown',true),
    (44,'elizabeth.davis@example.com','$2a$10$abcdefghijklmnopqrstuv','Elizabeth','Davis',true),
    (45,'james.wilson@example.com','$2a$10$abcdefghijklmnopqrstuv','James','Wilson',true),
    (46,'mary.taylor@example.com','$2a$10$abcdefghijklmnopqrstuv','Mary','Taylor',true),
    (47,'robert.anderson@example.com','$2a$10$abcdefghijklmnopqrstuv','Robert','Anderson',true),
    (48,'patricia.thomas@example.com','$2a$10$abcdefghijklmnopqrstuv','Patricia','Thomas',true),
    (49,'david.jackson@example.com','$2a$10$abcdefghijklmnopqrstuv','David','Jackson',true),
    (50,'linda.white@example.com','$2a$10$abcdefghijklmnopqrstuv','Linda','White',true),

    (51,'martin.robinson@example.com','$2a$10$abcdefghijklmnopqrstuv','Martin','Robinson',true),
    (52,'sophie.edwards@example.com','$2a$10$abcdefghijklmnopqrstuv','Sophie','Edwards',true),
    (53,'alexandre.bernard@example.com','$2a$10$abcdefghijklmnopqrstuv','Alexandre','Bernard',true),
    (54,'chloe.fontaine@example.com','$2a$10$abcdefghijklmnopqrstuv','Chloé','Fontaine',true),
    (55,'laurent.marchand@example.com','$2a$10$abcdefghijklmnopqrstuv','Laurent','Marchand',true),
    (56,'isabelle.garnier@example.com','$2a$10$abcdefghijklmnopqrstuv','Isabelle','Garnier',true),
    (57,'sebastien.girard@example.com','$2a$10$abcdefghijklmnopqrstuv','Sébastien','Girard',true),
    (58,'manon.petitjean@example.com','$2a$10$abcdefghijklmnopqrstuv','Manon','Petitjean',true),
    (59,'olivier.dupuis@example.com','$2a$10$abcdefghijklmnopqrstuv','Olivier','Dupuis',true),
    (60,'juliette.renault@example.com','$2a$10$abcdefghijklmnopqrstuv','Juliette','Renault',true),

    (61,'hugo.rousseau@example.com','$2a$10$abcdefghijklmnopqrstuv','Hugo','Rousseau',true),
    (62,'elise.fontaine@example.com','$2a$10$abcdefghijklmnopqrstuv','Élise','Fontaine',true),
    (63,'pascal.martin@example.com','$2a$10$abcdefghijklmnopqrstuv','Pascal','Martin',true),
    (64,'claire.fournier@example.com','$2a$10$abcdefghijklmnopqrstuv','Claire','Fournier',true),
    (65,'laurent.morel@example.com','$2a$10$abcdefghijklmnopqrstuv','Laurent','Morel',true),
    (66,'amandine.caron@example.com','$2a$10$abcdefghijklmnopqrstuv','Amandine','Caron',true),
    (67,'vincent.lefevre@example.com','$2a$10$abcdefghijklmnopqrstuv','Vincent','Lefèvre',true),
    (68,'audrey.mercier@example.com','$2a$10$abcdefghijklmnopqrstuv','Audrey','Mercier',true),
    (69,'romain.gauthier@example.com','$2a$10$abcdefghijklmnopqrstuv','Romain','Gauthier',true),
    (70,'marine.dupont@example.com','$2a$10$abcdefghijklmnopqrstuv','Marine','Dupont',true),

    (71,'dirk.vermeer@example.com','$2a$10$abcdefghijklmnopqrstuv','Dirk','Vermeer',true),
    (72,'anke.vandenberg@example.com','$2a$10$abcdefghijklmnopqrstuv','Anke','Van den Berg',true),
    (73,'tim.dejong@example.com','$2a$10$abcdefghijklmnopqrstuv','Tim','De Jong',true),
    (74,'eva.degraaf@example.com','$2a$10$abcdefghijklmnopqrstuv','Eva','De Graaf',true),
    (75,'joost.deruiter@example.com','$2a$10$abcdefghijklmnopqrstuv','Joost','De Ruiter',true),
    (76,'lisa.veenstra@example.com','$2a$10$abcdefghijklmnopqrstuv','Lisa','Veenstra',true),
    (77,'bas.mulder@example.com','$2a$10$abcdefghijklmnopqrstuv','Bas','Mulder',true),
    (78,'marieke.deklerk@example.com','$2a$10$abcdefghijklmnopqrstuv','Marieke','De Klerk',true),
    (79,'rik.bos@example.com','$2a$10$abcdefghijklmnopqrstuv','Rik','Bos',true),
    (80,'sander.devries@example.com','$2a$10$abcdefghijklmnopqrstuv','Sander','De Vries',true),

    (81,'oliver.jones@example.com','$2a$10$abcdefghijklmnopqrstuv','Oliver','Jones',true),
    (82,'amelia.harris@example.com','$2a$10$abcdefghijklmnopqrstuv','Amelia','Harris',true),
    (83,'benjamin.thompson@example.com','$2a$10$abcdefghijklmnopqrstuv','Benjamin','Thompson',true),
    (84,'charlotte.martin@example.com','$2a$10$abcdefghijklmnopqrstuv','Charlotte','Martin',true),
    (85,'henry.walker@example.com','$2a$10$abcdefghijklmnopqrstuv','Henry','Walker',true),
    (86,'grace.robinson@example.com','$2a$10$abcdefghijklmnopqrstuv','Grace','Robinson',true),
    (87,'samuel.lewis@example.com','$2a$10$abcdefghijklmnopqrstuv','Samuel','Lewis',true),
    (88,'victoria.clark@example.com','$2a$10$abcdefghijklmnopqrstuv','Victoria','Clark',true),
    (89,'jack.hall@example.com','$2a$10$abcdefghijklmnopqrstuv','Jack','Hall',true),
    (90,'emily.allen@example.com','$2a$10$abcdefghijklmnopqrstuv','Emily','Allen',true),

    (91,'mathieu.bernard@example.com','$2a$10$abcdefghijklmnopqrstuv','Mathieu','Bernard',true),
    (92,'fiona.gallagher@example.com','$2a$10$abcdefghijklmnopqrstuv','Fiona','Gallagher',true),
    (93,'sophie.rousseau@example.com','$2a$10$abcdefghijklmnopqrstuv','Sophie','Rousseau',true),
    (94,'leo.gibson@example.com','$2a$10$abcdefghijklmnopqrstuv','Leo','Gibson',true),
    (95,'emma.cooper@example.com','$2a$10$abcdefghijklmnopqrstuv','Emma','Cooper',true),
    (96,'liam.carter@example.com','$2a$10$abcdefghijklmnopqrstuv','Liam','Carter',true),
    (97,'zoe.marshall@example.com','$2a$10$abcdefghijklmnopqrstuv','Zoe','Marshall',true),
    (98,'mason.scott@example.com','$2a$10$abcdefghijklmnopqrstuv','Mason','Scott',true),
    (99,'ava.peterson@example.com','$2a$10$abcdefghijklmnopqrstuv','Ava','Peterson',true),
    (100,'oliver.wright@example.com','$2a$10$abcdefghijklmnopqrstuv','Oliver','Wright',true);
