INSERT INTO activity (
    title, description, price, duration_minutes, minimum_age, equipment_information,
    status, reviewed_at, reviewed_by_user_id, partner_id
) VALUES
('Yoga du matin', 'Séance de yoga accessible aux débutants.', 18.00, 60, 6, 'Tenue confortable et tapis conseillé.', 'APPROVED', CURRENT_TIMESTAMP, 3, 1),
('Escape game — Le dernier train', 'Jeu immersif en équipe avec énigmes.', 32.00, 90, 12, 'Aucun matériel nécessaire.', 'APPROVED', CURRENT_TIMESTAMP, 3, 2),
('Atelier pâtes fraîches', 'Préparation guidée d’une recette et dégustation.', 42.00, 120, 6, 'Tablier conseillé.', 'APPROVED', CURRENT_TIMESTAMP, 3, 3),
('Initiation à l’escalade en salle', 'Découverte de l’escalade avec encadrement.', 28.00, 90, 10, 'Chaussures de sport obligatoires.', 'APPROVED', CURRENT_TIMESTAMP, 3, 4),
('Randonnée guidée en Forêt de Soignes', 'Parcours en extérieur accompagné par un guide.', 15.00, 150, 6, 'Chaussures de marche et bouteille d’eau.', 'APPROVED', CURRENT_TIMESTAMP, 3, 5),
('Partie de paintball en forêt', 'Partie de paintball encadrée avec équipement fourni.', 35.00, 120, 14, 'Équipement de protection fourni.', 'APPROVED', CURRENT_TIMESTAMP, 3, 6),
('Cours de fitness collectif', 'Cours collectif adapté au niveau des participants.', 20.00, 75, 6, 'Tenue souple et chaussures adaptées.', 'APPROVED', CURRENT_TIMESTAMP, 3, 7),
('Atelier peinture acrylique', 'Sortie à vélo avec itinéraire préparé.', 22.00, 120, 6, 'Casque fourni. Tenue sportive conseillée.', 'APPROVED', CURRENT_TIMESTAMP, 3, 8),
('Balade à vélo dans Bruxelles', 'Atelier manuel avec matériel mis à disposition.', 16.00, 90, 6, 'Matériel fourni sur place.', 'APPROVED', CURRENT_TIMESTAMP, 3, 9),
('Aquagym', 'Séance sportive collective avec accompagnement.', 24.00, 60, 6, 'Tenue sportive et bouteille d’eau.', 'APPROVED', CURRENT_TIMESTAMP, 3, 10),
('Séance de méditation guidée', 'Séance de yoga accessible aux débutants.', 18.00, 60, 6, 'Tenue confortable et tapis conseillé.', 'APPROVED', CURRENT_TIMESTAMP, 3, 11),
('Parcours accrobranche', 'Jeu immersif en équipe avec énigmes.', 32.00, 90, 12, 'Aucun matériel nécessaire.', 'APPROVED', CURRENT_TIMESTAMP, 3, 12),
('Cours de salsa débutant', 'Préparation guidée d’une recette et dégustation.', 42.00, 120, 6, 'Tablier conseillé.', 'APPROVED', CURRENT_TIMESTAMP, 3, 13),
('Initiation au paddle', 'Découverte de l’escalade avec encadrement.', 28.00, 90, 10, 'Chaussures de sport obligatoires.', 'APPROVED', CURRENT_TIMESTAMP, 3, 14),
('Atelier bricolage enfants', 'Parcours en extérieur accompagné par un guide.', 15.00, 150, 6, 'Chaussures de marche et bouteille d’eau.', 'APPROVED', CURRENT_TIMESTAMP, 3, 15),
('Sortie course à pied guidée', 'Partie de paintball encadrée avec équipement fourni.', 35.00, 120, 14, 'Équipement de protection fourni.', 'APPROVED', CURRENT_TIMESTAMP, 3, 16),
('Balade photo dans le centre', 'Cours collectif adapté au niveau des participants.', 20.00, 75, 6, 'Tenue souple et chaussures adaptées.', 'APPROVED', CURRENT_TIMESTAMP, 3, 17),
('Balade à cheval en forêt', 'Sortie à vélo avec itinéraire préparé.', 22.00, 120, 6, 'Casque fourni. Tenue sportive conseillée.', 'APPROVED', CURRENT_TIMESTAMP, 3, 18),
('Initiation au badminton', 'Atelier manuel avec matériel mis à disposition.', 16.00, 90, 6, 'Matériel fourni sur place.', 'APPROVED', CURRENT_TIMESTAMP, 3, 19),
('Escalade urbaine encadrée', 'Séance sportive collective avec accompagnement.', 24.00, 60, 6, 'Tenue sportive et bouteille d’eau.', 'APPROVED', CURRENT_TIMESTAMP, 3, 20),
('Atelier pleine conscience', 'Séance de yoga accessible aux débutants.', 18.00, 60, 6, 'Tenue confortable et tapis conseillé.', 'APPROVED', CURRENT_TIMESTAMP, 3, 21),
('Descente en kayak', 'Jeu immersif en équipe avec énigmes.', 32.00, 90, 12, 'Aucun matériel nécessaire.', 'APPROVED', CURRENT_TIMESTAMP, 3, 22),
('Soirée jeux de société', 'Préparation guidée d’une recette et dégustation.', 42.00, 120, 6, 'Tablier conseillé.', 'APPROVED', CURRENT_TIMESTAMP, 3, 23),
('Circuit training', 'Découverte de l’escalade avec encadrement.', 28.00, 90, 10, 'Chaussures de sport obligatoires.', 'APPROVED', CURRENT_TIMESTAMP, 3, 24),
('Atelier tournage céramique', 'Parcours en extérieur accompagné par un guide.', 15.00, 150, 6, 'Chaussures de marche et bouteille d’eau.', 'APPROVED', CURRENT_TIMESTAMP, 3, 25),
('Trail découverte en Ardenne', 'Partie de paintball encadrée avec équipement fourni.', 35.00, 120, 14, 'Équipement de protection fourni.', 'APPROVED', CURRENT_TIMESTAMP, 3, 26),
('Atelier percussions', 'Cours collectif adapté au niveau des participants.', 20.00, 75, 6, 'Tenue souple et chaussures adaptées.', 'APPROVED', CURRENT_TIMESTAMP, 3, 27),
('Initiation au skateboard', 'Sortie à vélo avec itinéraire préparé.', 22.00, 120, 6, 'Casque fourni. Tenue sportive conseillée.', 'APPROVED', CURRENT_TIMESTAMP, 3, 28),
('Atelier potager urbain', 'Atelier manuel avec matériel mis à disposition.', 16.00, 90, 6, 'Matériel fourni sur place.', 'APPROVED', CURRENT_TIMESTAMP, 3, 29),
('Initiation au tir à l’arc', 'Séance sportive collective avec accompagnement.', 24.00, 60, 6, 'Tenue sportive et bouteille d’eau.', 'APPROVED', CURRENT_TIMESTAMP, 3, 30),
('Atelier chocolat belge', 'Séance de yoga accessible aux débutants.', 18.00, 60, 6, 'Tenue confortable et tapis conseillé.', 'APPROVED', CURRENT_TIMESTAMP, 3, 31),
('Initiation à la voile', 'Jeu immersif en équipe avec énigmes.', 32.00, 90, 12, 'Aucun matériel nécessaire.', 'APPROVED', CURRENT_TIMESTAMP, 3, 32),
('Atelier d’improvisation', 'Préparation guidée d’une recette et dégustation.', 42.00, 120, 6, 'Tablier conseillé.', 'APPROVED', CURRENT_TIMESTAMP, 3, 33),
('Initiation à la boxe anglaise', 'Découverte de l’escalade avec encadrement.', 28.00, 90, 10, 'Chaussures de sport obligatoires.', 'APPROVED', CURRENT_TIMESTAMP, 3, 34),
('Atelier robotique enfants', 'Parcours en extérieur accompagné par un guide.', 15.00, 150, 6, 'Chaussures de marche et bouteille d’eau.', 'APPROVED', CURRENT_TIMESTAMP, 3, 35),
('Initiation au golf sur practice', 'Partie de paintball encadrée avec équipement fourni.', 35.00, 120, 14, 'Équipement de protection fourni.', 'APPROVED', CURRENT_TIMESTAMP, 3, 36),
('Accès spa et sauna', 'Cours collectif adapté au niveau des participants.', 20.00, 75, 6, 'Tenue souple et chaussures adaptées.', 'APPROVED', CURRENT_TIMESTAMP, 3, 37),
('Visite guidée du centre historique', 'Sortie à vélo avec itinéraire préparé.', 22.00, 120, 6, 'Casque fourni. Tenue sportive conseillée.', 'APPROVED', CURRENT_TIMESTAMP, 3, 38),
('Atelier cuisine pour enfants', 'Atelier manuel avec matériel mis à disposition.', 16.00, 90, 6, 'Matériel fourni sur place.', 'APPROVED', CURRENT_TIMESTAMP, 3, 39),
('Parcours d’obstacles en équipe', 'Séance sportive collective avec accompagnement.', 24.00, 60, 6, 'Tenue sportive et bouteille d’eau.', 'APPROVED', CURRENT_TIMESTAMP, 3, 40),
('Yoga doux et respiration', 'Séance de yoga accessible aux débutants.', 18.00, 60, 6, 'Tenue confortable et tapis conseillé.', 'APPROVED', CURRENT_TIMESTAMP, 3, 1),
('Escape game — Le laboratoire', 'Jeu immersif en équipe avec énigmes.', 32.00, 90, 12, 'Aucun matériel nécessaire.', 'APPROVED', CURRENT_TIMESTAMP, 3, 2),
('Atelier cuisine du monde', 'Préparation guidée d’une recette et dégustation.', 42.00, 120, 6, 'Tablier conseillé.', 'APPROVED', CURRENT_TIMESTAMP, 3, 3),
('Escalade de bloc', 'Découverte de l’escalade avec encadrement.', 28.00, 90, 10, 'Chaussures de sport obligatoires.', 'APPROVED', CURRENT_TIMESTAMP, 3, 4),
('Marche nordique', 'Parcours en extérieur accompagné par un guide.', 15.00, 150, 6, 'Chaussures de marche et bouteille d’eau.', 'APPROVED', CURRENT_TIMESTAMP, 3, 5),
('Paintball scénarisé', 'Partie de paintball encadrée avec équipement fourni.', 35.00, 120, 14, 'Équipement de protection fourni.', 'APPROVED', CURRENT_TIMESTAMP, 3, 6),
('Renforcement musculaire', 'Cours collectif adapté au niveau des participants.', 20.00, 75, 6, 'Tenue souple et chaussures adaptées.', 'APPROVED', CURRENT_TIMESTAMP, 3, 7),
('Atelier collage et papier', 'Sortie à vélo avec itinéraire préparé.', 22.00, 120, 6, 'Casque fourni. Tenue sportive conseillée.', 'APPROVED', CURRENT_TIMESTAMP, 3, 8),
('Sortie vélo le long du canal', 'Atelier manuel avec matériel mis à disposition.', 16.00, 90, 6, 'Matériel fourni sur place.', 'APPROVED', CURRENT_TIMESTAMP, 3, 9),
('Initiation à la natation adulte', 'Séance sportive collective avec accompagnement.', 24.00, 60, 6, 'Tenue sportive et bouteille d’eau.', 'APPROVED', CURRENT_TIMESTAMP, 3, 10),
('Pilates débutant', 'Séance de yoga accessible aux débutants.', 18.00, 60, 6, 'Tenue confortable et tapis conseillé.', 'APPROVED', CURRENT_TIMESTAMP, 3, 11),
('Tyrolienne géante', 'Jeu immersif en équipe avec énigmes.', 32.00, 90, 12, 'Aucun matériel nécessaire.', 'APPROVED', CURRENT_TIMESTAMP, 3, 12),
('Danse contemporaine', 'Préparation guidée d’une recette et dégustation.', 42.00, 120, 6, 'Tablier conseillé.', 'APPROVED', CURRENT_TIMESTAMP, 3, 13),
('Balade en paddle sur la Meuse', 'Découverte de l’escalade avec encadrement.', 28.00, 90, 10, 'Chaussures de sport obligatoires.', 'APPROVED', CURRENT_TIMESTAMP, 3, 14),
('Après-midi jeux et éveil', 'Parcours en extérieur accompagné par un guide.', 15.00, 150, 6, 'Chaussures de marche et bouteille d’eau.', 'APPROVED', CURRENT_TIMESTAMP, 3, 15),
('Entraînement fractionné', 'Partie de paintball encadrée avec équipement fourni.', 35.00, 120, 14, 'Équipement de protection fourni.', 'APPROVED', CURRENT_TIMESTAMP, 3, 16),
('Atelier photo de nuit', 'Cours collectif adapté au niveau des participants.', 20.00, 75, 6, 'Tenue souple et chaussures adaptées.', 'APPROVED', CURRENT_TIMESTAMP, 3, 17),
('Initiation à l’équitation', 'Sortie à vélo avec itinéraire préparé.', 22.00, 120, 6, 'Casque fourni. Tenue sportive conseillée.', 'APPROVED', CURRENT_TIMESTAMP, 3, 18),
('Cours de tennis débutant', 'Atelier manuel avec matériel mis à disposition.', 16.00, 90, 6, 'Matériel fourni sur place.', 'APPROVED', CURRENT_TIMESTAMP, 3, 19),
('Bloc et technique', 'Séance sportive collective avec accompagnement.', 24.00, 60, 6, 'Tenue sportive et bouteille d’eau.', 'APPROVED', CURRENT_TIMESTAMP, 3, 20),
('Marche méditative', 'Séance de yoga accessible aux débutants.', 18.00, 60, 6, 'Tenue confortable et tapis conseillé.', 'APPROVED', CURRENT_TIMESTAMP, 3, 21),
('Initiation au canoë', 'Jeu immersif en équipe avec énigmes.', 32.00, 90, 12, 'Aucun matériel nécessaire.', 'APPROVED', CURRENT_TIMESTAMP, 3, 22),
('Initiation aux jeux de stratégie', 'Préparation guidée d’une recette et dégustation.', 42.00, 120, 6, 'Tablier conseillé.', 'APPROVED', CURRENT_TIMESTAMP, 3, 23),
('Cours de HIIT', 'Découverte de l’escalade avec encadrement.', 28.00, 90, 10, 'Chaussures de sport obligatoires.', 'APPROVED', CURRENT_TIMESTAMP, 3, 24),
('Modelage et émaillage', 'Parcours en extérieur accompagné par un guide.', 15.00, 150, 6, 'Chaussures de marche et bouteille d’eau.', 'APPROVED', CURRENT_TIMESTAMP, 3, 25),
('Sortie trail nocturne', 'Partie de paintball encadrée avec équipement fourni.', 35.00, 120, 14, 'Équipement de protection fourni.', 'APPROVED', CURRENT_TIMESTAMP, 3, 26),
('Initiation à la guitare', 'Cours collectif adapté au niveau des participants.', 20.00, 75, 6, 'Tenue souple et chaussures adaptées.', 'APPROVED', CURRENT_TIMESTAMP, 3, 27),
('Roller débutant', 'Sortie à vélo avec itinéraire préparé.', 22.00, 120, 6, 'Casque fourni. Tenue sportive conseillée.', 'APPROVED', CURRENT_TIMESTAMP, 3, 28),
('Initiation à la permaculture', 'Atelier manuel avec matériel mis à disposition.', 16.00, 90, 6, 'Matériel fourni sur place.', 'APPROVED', CURRENT_TIMESTAMP, 3, 29),
('Tir à l’arc en extérieur', 'Séance sportive collective avec accompagnement.', 24.00, 60, 6, 'Tenue sportive et bouteille d’eau.', 'APPROVED', CURRENT_TIMESTAMP, 3, 30),
('Fabrication de pralines', 'Séance de yoga accessible aux débutants.', 18.00, 60, 6, 'Tenue confortable et tapis conseillé.', 'APPROVED', CURRENT_TIMESTAMP, 3, 31),
('Sortie catamaran', 'Jeu immersif en équipe avec énigmes.', 32.00, 90, 12, 'Aucun matériel nécessaire.', 'APPROVED', CURRENT_TIMESTAMP, 3, 32),
('Initiation au théâtre', 'Préparation guidée d’une recette et dégustation.', 42.00, 120, 6, 'Tablier conseillé.', 'APPROVED', CURRENT_TIMESTAMP, 3, 33),
('Cours de boxe fitness', 'Découverte de l’escalade avec encadrement.', 28.00, 90, 10, 'Chaussures de sport obligatoires.', 'APPROVED', CURRENT_TIMESTAMP, 3, 34),
('Initiation à la programmation', 'Parcours en extérieur accompagné par un guide.', 15.00, 150, 6, 'Chaussures de marche et bouteille d’eau.', 'APPROVED', CURRENT_TIMESTAMP, 3, 35),
('Parcours découverte 9 trous', 'Partie de paintball encadrée avec équipement fourni.', 35.00, 120, 14, 'Équipement de protection fourni.', 'APPROVED', CURRENT_TIMESTAMP, 3, 36),
('Massage relaxant', 'Cours collectif adapté au niveau des participants.', 20.00, 75, 6, 'Tenue souple et chaussures adaptées.', 'APPROVED', CURRENT_TIMESTAMP, 3, 37),
('Balade street art', 'Sortie à vélo avec itinéraire préparé.', 22.00, 120, 6, 'Casque fourni. Tenue sportive conseillée.', 'APPROVED', CURRENT_TIMESTAMP, 3, 38),
('Atelier goûter maison', 'Atelier manuel avec matériel mis à disposition.', 16.00, 90, 6, 'Matériel fourni sur place.', 'APPROVED', CURRENT_TIMESTAMP, 3, 39),
('Course d’orientation', 'Séance sportive collective avec accompagnement.', 24.00, 60, 6, 'Tenue sportive et bouteille d’eau.', 'APPROVED', CURRENT_TIMESTAMP, 3, 40),
('Vinyasa flow', 'Séance de yoga accessible aux débutants.', 18.00, 60, 6, 'Tenue confortable et tapis conseillé.', 'APPROVED', CURRENT_TIMESTAMP, 3, 1),
('Escape game — Le phare oublié', 'Jeu immersif en équipe avec énigmes.', 32.00, 90, 12, 'Aucun matériel nécessaire.', 'APPROVED', CURRENT_TIMESTAMP, 3, 2),
('Atelier pâtisserie belge', 'Préparation guidée d’une recette et dégustation.', 42.00, 120, 6, 'Tablier conseillé.', 'APPROVED', CURRENT_TIMESTAMP, 3, 3),
('Voie extérieure encadrée', 'Découverte de l’escalade avec encadrement.', 28.00, 90, 10, 'Chaussures de sport obligatoires.', 'APPROVED', CURRENT_TIMESTAMP, 3, 4),
('Sortie nature en famille', 'Parcours en extérieur accompagné par un guide.', 15.00, 150, 6, 'Chaussures de marche et bouteille d’eau.', 'APPROVED', CURRENT_TIMESTAMP, 3, 5),
('Initiation paintball ados', 'Partie de paintball encadrée avec équipement fourni.', 35.00, 120, 14, 'Équipement de protection fourni.', 'APPROVED', CURRENT_TIMESTAMP, 3, 6),
('Stretching et mobilité', 'Cours collectif adapté au niveau des participants.', 20.00, 75, 6, 'Tenue souple et chaussures adaptées.', 'APPROVED', CURRENT_TIMESTAMP, 3, 7),
('Atelier carnet de voyage', 'Sortie à vélo avec itinéraire préparé.', 22.00, 120, 6, 'Casque fourni. Tenue sportive conseillée.', 'APPROVED', CURRENT_TIMESTAMP, 3, 8),
('Randonnée cycliste en Brabant', 'Atelier manuel avec matériel mis à disposition.', 16.00, 90, 6, 'Matériel fourni sur place.', 'APPROVED', CURRENT_TIMESTAMP, 3, 9),
('Aquabike', 'Séance sportive collective avec accompagnement.', 24.00, 60, 6, 'Tenue sportive et bouteille d’eau.', 'APPROVED', CURRENT_TIMESTAMP, 3, 10),
('Relaxation sonore', 'Séance de yoga accessible aux débutants.', 18.00, 60, 6, 'Tenue confortable et tapis conseillé.', 'APPROVED', CURRENT_TIMESTAMP, 3, 11),
('Parcours aventure enfants', 'Jeu immersif en équipe avec énigmes.', 32.00, 90, 12, 'Aucun matériel nécessaire.', 'APPROVED', CURRENT_TIMESTAMP, 3, 12),
('Initiation hip-hop', 'Préparation guidée d’une recette et dégustation.', 42.00, 120, 6, 'Tablier conseillé.', 'APPROVED', CURRENT_TIMESTAMP, 3, 13),
('Paddle yoga', 'Découverte de l’escalade avec encadrement.', 28.00, 90, 10, 'Chaussures de sport obligatoires.', 'APPROVED', CURRENT_TIMESTAMP, 3, 14),
('Atelier science pour enfants', 'Parcours en extérieur accompagné par un guide.', 15.00, 150, 6, 'Chaussures de marche et bouteille d’eau.', 'APPROVED', CURRENT_TIMESTAMP, 3, 15),
('Run découverte du parc', 'Partie de paintball encadrée avec équipement fourni.', 35.00, 120, 14, 'Équipement de protection fourni.', 'APPROVED', CURRENT_TIMESTAMP, 3, 16),
('Initiation au portrait', 'Cours collectif adapté au niveau des participants.', 20.00, 75, 6, 'Tenue souple et chaussures adaptées.', 'APPROVED', CURRENT_TIMESTAMP, 3, 17),
('Soins et découverte du poney', 'Sortie à vélo avec itinéraire préparé.', 22.00, 120, 6, 'Casque fourni. Tenue sportive conseillée.', 'APPROVED', CURRENT_TIMESTAMP, 3, 18),
('Tournoi de squash amateur', 'Atelier manuel avec matériel mis à disposition.', 16.00, 90, 6, 'Matériel fourni sur place.', 'APPROVED', CURRENT_TIMESTAMP, 3, 19),
('Escalade en nocturne', 'Séance sportive collective avec accompagnement.', 24.00, 60, 6, 'Tenue sportive et bouteille d’eau.', 'APPROVED', CURRENT_TIMESTAMP, 3, 20);