INSERT INTO activity (
    title, description, price, duration_minutes,
    minimum_age, equipment_information, active, partner_id
) VALUES
('Cours de yoga #001', 'Séance de yoga accessible aux débutants.', 18.00, 60, 6, 'Tenue confortable et tapis conseillé.', TRUE, 1),
('Escape game #002', 'Jeu immersif en équipe avec énigmes.', 32.00, 90, 12, 'Aucun matériel nécessaire.', TRUE, 2),
('Atelier cuisine #003', 'Préparation guidée d’une recette et dégustation.', 42.00, 120, 6, 'Tablier conseillé.', TRUE, 3),
('Initiation escalade #004', 'Découverte de l’escalade avec encadrement.', 28.00, 90, 10, 'Chaussures de sport obligatoires.', TRUE, 4),
('Randonnée guidée #005', 'Parcours en extérieur accompagné par un guide.', 15.00, 150, 6, 'Chaussures de marche et bouteille d’eau.', TRUE, 5),
('Session paintball #006', 'Partie de paintball encadrée avec équipement fourni.', 35.00, 120, 14, 'Équipement de protection fourni.', TRUE, 6),
('Cours de danse #007', 'Cours collectif adapté au niveau des participants.', 20.00, 75, 6, 'Tenue souple et chaussures adaptées.', TRUE, 7),
('Balade à vélo #008', 'Sortie à vélo avec itinéraire préparé.', 22.00, 120, 6, 'Casque fourni. Tenue sportive conseillée.', TRUE, 8),
('Atelier créatif #009', 'Atelier manuel avec matériel mis à disposition.', 16.00, 90, 6, 'Matériel fourni sur place.', TRUE, 9),
('Séance de remise en forme #010', 'Séance sportive collective avec accompagnement.', 24.00, 60, 6, 'Tenue sportive et bouteille d’eau.', TRUE, 10),
('Cours de yoga #011', 'Séance de yoga accessible aux débutants.', 18.00, 60, 6, 'Tenue confortable et tapis conseillé.', TRUE, 11),
('Escape game #012', 'Jeu immersif en équipe avec énigmes.', 32.00, 90, 12, 'Aucun matériel nécessaire.', TRUE, 12),
('Atelier cuisine #013', 'Préparation guidée d’une recette et dégustation.', 42.00, 120, 6, 'Tablier conseillé.', TRUE, 13),
('Initiation escalade #014', 'Découverte de l’escalade avec encadrement.', 28.00, 90, 10, 'Chaussures de sport obligatoires.', TRUE, 14),
('Randonnée guidée #015', 'Parcours en extérieur accompagné par un guide.', 15.00, 150, 6, 'Chaussures de marche et bouteille d’eau.', TRUE, 15),
('Session paintball #016', 'Partie de paintball encadrée avec équipement fourni.', 35.00, 120, 14, 'Équipement de protection fourni.', TRUE, 16),
('Cours de danse #017', 'Cours collectif adapté au niveau des participants.', 20.00, 75, 6, 'Tenue souple et chaussures adaptées.', TRUE, 17),
('Balade à vélo #018', 'Sortie à vélo avec itinéraire préparé.', 22.00, 120, 6, 'Casque fourni. Tenue sportive conseillée.', TRUE, 18),
('Atelier créatif #019', 'Atelier manuel avec matériel mis à disposition.', 16.00, 90, 6, 'Matériel fourni sur place.', TRUE, 19),
('Séance de remise en forme #020', 'Séance sportive collective avec accompagnement.', 24.00, 60, 6, 'Tenue sportive et bouteille d’eau.', TRUE, 20),
('Cours de yoga #021', 'Séance de yoga accessible aux débutants.', 18.00, 60, 6, 'Tenue confortable et tapis conseillé.', TRUE, 21),
('Escape game #022', 'Jeu immersif en équipe avec énigmes.', 32.00, 90, 12, 'Aucun matériel nécessaire.', TRUE, 22),
('Atelier cuisine #023', 'Préparation guidée d’une recette et dégustation.', 42.00, 120, 6, 'Tablier conseillé.', TRUE, 23),
('Initiation escalade #024', 'Découverte de l’escalade avec encadrement.', 28.00, 90, 10, 'Chaussures de sport obligatoires.', TRUE, 24),
('Randonnée guidée #025', 'Parcours en extérieur accompagné par un guide.', 15.00, 150, 6, 'Chaussures de marche et bouteille d’eau.', TRUE, 25),
('Session paintball #026', 'Partie de paintball encadrée avec équipement fourni.', 35.00, 120, 14, 'Équipement de protection fourni.', TRUE, 26),
('Cours de danse #027', 'Cours collectif adapté au niveau des participants.', 20.00, 75, 6, 'Tenue souple et chaussures adaptées.', TRUE, 27),
('Balade à vélo #028', 'Sortie à vélo avec itinéraire préparé.', 22.00, 120, 6, 'Casque fourni. Tenue sportive conseillée.', TRUE, 28),
('Atelier créatif #029', 'Atelier manuel avec matériel mis à disposition.', 16.00, 90, 6, 'Matériel fourni sur place.', TRUE, 29),
('Séance de remise en forme #030', 'Séance sportive collective avec accompagnement.', 24.00, 60, 6, 'Tenue sportive et bouteille d’eau.', TRUE, 30),
('Cours de yoga #031', 'Séance de yoga accessible aux débutants.', 18.00, 60, 6, 'Tenue confortable et tapis conseillé.', TRUE, 31),
('Escape game #032', 'Jeu immersif en équipe avec énigmes.', 32.00, 90, 12, 'Aucun matériel nécessaire.', TRUE, 32),
('Atelier cuisine #033', 'Préparation guidée d’une recette et dégustation.', 42.00, 120, 6, 'Tablier conseillé.', TRUE, 33),
('Initiation escalade #034', 'Découverte de l’escalade avec encadrement.', 28.00, 90, 10, 'Chaussures de sport obligatoires.', TRUE, 34),
('Randonnée guidée #035', 'Parcours en extérieur accompagné par un guide.', 15.00, 150, 6, 'Chaussures de marche et bouteille d’eau.', TRUE, 35),
('Session paintball #036', 'Partie de paintball encadrée avec équipement fourni.', 35.00, 120, 14, 'Équipement de protection fourni.', TRUE, 36),
('Cours de danse #037', 'Cours collectif adapté au niveau des participants.', 20.00, 75, 6, 'Tenue souple et chaussures adaptées.', TRUE, 37),
('Balade à vélo #038', 'Sortie à vélo avec itinéraire préparé.', 22.00, 120, 6, 'Casque fourni. Tenue sportive conseillée.', TRUE, 38),
('Atelier créatif #039', 'Atelier manuel avec matériel mis à disposition.', 16.00, 90, 6, 'Matériel fourni sur place.', TRUE, 39),
('Séance de remise en forme #040', 'Séance sportive collective avec accompagnement.', 24.00, 60, 6, 'Tenue sportive et bouteille d’eau.', TRUE, 40),
('Cours de yoga #041', 'Séance de yoga accessible aux débutants.', 18.00, 60, 6, 'Tenue confortable et tapis conseillé.', TRUE, 1),
('Escape game #042', 'Jeu immersif en équipe avec énigmes.', 32.00, 90, 12, 'Aucun matériel nécessaire.', TRUE, 2),
('Atelier cuisine #043', 'Préparation guidée d’une recette et dégustation.', 42.00, 120, 6, 'Tablier conseillé.', TRUE, 3),
('Initiation escalade #044', 'Découverte de l’escalade avec encadrement.', 28.00, 90, 10, 'Chaussures de sport obligatoires.', TRUE, 4),
('Randonnée guidée #045', 'Parcours en extérieur accompagné par un guide.', 15.00, 150, 6, 'Chaussures de marche et bouteille d’eau.', TRUE, 5),
('Session paintball #046', 'Partie de paintball encadrée avec équipement fourni.', 35.00, 120, 14, 'Équipement de protection fourni.', TRUE, 6),
('Cours de danse #047', 'Cours collectif adapté au niveau des participants.', 20.00, 75, 6, 'Tenue souple et chaussures adaptées.', TRUE, 7),
('Balade à vélo #048', 'Sortie à vélo avec itinéraire préparé.', 22.00, 120, 6, 'Casque fourni. Tenue sportive conseillée.', TRUE, 8),
('Atelier créatif #049', 'Atelier manuel avec matériel mis à disposition.', 16.00, 90, 6, 'Matériel fourni sur place.', TRUE, 9),
('Séance de remise en forme #050', 'Séance sportive collective avec accompagnement.', 24.00, 60, 6, 'Tenue sportive et bouteille d’eau.', TRUE, 10),
('Cours de yoga #051', 'Séance de yoga accessible aux débutants.', 18.00, 60, 6, 'Tenue confortable et tapis conseillé.', TRUE, 11),
('Escape game #052', 'Jeu immersif en équipe avec énigmes.', 32.00, 90, 12, 'Aucun matériel nécessaire.', TRUE, 12),
('Atelier cuisine #053', 'Préparation guidée d’une recette et dégustation.', 42.00, 120, 6, 'Tablier conseillé.', TRUE, 13),
('Initiation escalade #054', 'Découverte de l’escalade avec encadrement.', 28.00, 90, 10, 'Chaussures de sport obligatoires.', TRUE, 14),
('Randonnée guidée #055', 'Parcours en extérieur accompagné par un guide.', 15.00, 150, 6, 'Chaussures de marche et bouteille d’eau.', TRUE, 15),
('Session paintball #056', 'Partie de paintball encadrée avec équipement fourni.', 35.00, 120, 14, 'Équipement de protection fourni.', TRUE, 16),
('Cours de danse #057', 'Cours collectif adapté au niveau des participants.', 20.00, 75, 6, 'Tenue souple et chaussures adaptées.', TRUE, 17),
('Balade à vélo #058', 'Sortie à vélo avec itinéraire préparé.', 22.00, 120, 6, 'Casque fourni. Tenue sportive conseillée.', TRUE, 18),
('Atelier créatif #059', 'Atelier manuel avec matériel mis à disposition.', 16.00, 90, 6, 'Matériel fourni sur place.', TRUE, 19),
('Séance de remise en forme #060', 'Séance sportive collective avec accompagnement.', 24.00, 60, 6, 'Tenue sportive et bouteille d’eau.', TRUE, 20),
('Cours de yoga #061', 'Séance de yoga accessible aux débutants.', 18.00, 60, 6, 'Tenue confortable et tapis conseillé.', TRUE, 21),
('Escape game #062', 'Jeu immersif en équipe avec énigmes.', 32.00, 90, 12, 'Aucun matériel nécessaire.', TRUE, 22),
('Atelier cuisine #063', 'Préparation guidée d’une recette et dégustation.', 42.00, 120, 6, 'Tablier conseillé.', TRUE, 23),
('Initiation escalade #064', 'Découverte de l’escalade avec encadrement.', 28.00, 90, 10, 'Chaussures de sport obligatoires.', TRUE, 24),
('Randonnée guidée #065', 'Parcours en extérieur accompagné par un guide.', 15.00, 150, 6, 'Chaussures de marche et bouteille d’eau.', TRUE, 25),
('Session paintball #066', 'Partie de paintball encadrée avec équipement fourni.', 35.00, 120, 14, 'Équipement de protection fourni.', TRUE, 26),
('Cours de danse #067', 'Cours collectif adapté au niveau des participants.', 20.00, 75, 6, 'Tenue souple et chaussures adaptées.', TRUE, 27),
('Balade à vélo #068', 'Sortie à vélo avec itinéraire préparé.', 22.00, 120, 6, 'Casque fourni. Tenue sportive conseillée.', TRUE, 28),
('Atelier créatif #069', 'Atelier manuel avec matériel mis à disposition.', 16.00, 90, 6, 'Matériel fourni sur place.', TRUE, 29),
('Séance de remise en forme #070', 'Séance sportive collective avec accompagnement.', 24.00, 60, 6, 'Tenue sportive et bouteille d’eau.', TRUE, 30),
('Cours de yoga #071', 'Séance de yoga accessible aux débutants.', 18.00, 60, 6, 'Tenue confortable et tapis conseillé.', TRUE, 31),
('Escape game #072', 'Jeu immersif en équipe avec énigmes.', 32.00, 90, 12, 'Aucun matériel nécessaire.', TRUE, 32),
('Atelier cuisine #073', 'Préparation guidée d’une recette et dégustation.', 42.00, 120, 6, 'Tablier conseillé.', TRUE, 33),
('Initiation escalade #074', 'Découverte de l’escalade avec encadrement.', 28.00, 90, 10, 'Chaussures de sport obligatoires.', TRUE, 34),
('Randonnée guidée #075', 'Parcours en extérieur accompagné par un guide.', 15.00, 150, 6, 'Chaussures de marche et bouteille d’eau.', TRUE, 35),
('Session paintball #076', 'Partie de paintball encadrée avec équipement fourni.', 35.00, 120, 14, 'Équipement de protection fourni.', TRUE, 36),
('Cours de danse #077', 'Cours collectif adapté au niveau des participants.', 20.00, 75, 6, 'Tenue souple et chaussures adaptées.', TRUE, 37),
('Balade à vélo #078', 'Sortie à vélo avec itinéraire préparé.', 22.00, 120, 6, 'Casque fourni. Tenue sportive conseillée.', TRUE, 38),
('Atelier créatif #079', 'Atelier manuel avec matériel mis à disposition.', 16.00, 90, 6, 'Matériel fourni sur place.', TRUE, 39),
('Séance de remise en forme #080', 'Séance sportive collective avec accompagnement.', 24.00, 60, 6, 'Tenue sportive et bouteille d’eau.', TRUE, 40),
('Cours de yoga #081', 'Séance de yoga accessible aux débutants.', 18.00, 60, 6, 'Tenue confortable et tapis conseillé.', TRUE, 1),
('Escape game #082', 'Jeu immersif en équipe avec énigmes.', 32.00, 90, 12, 'Aucun matériel nécessaire.', TRUE, 2),
('Atelier cuisine #083', 'Préparation guidée d’une recette et dégustation.', 42.00, 120, 6, 'Tablier conseillé.', TRUE, 3),
('Initiation escalade #084', 'Découverte de l’escalade avec encadrement.', 28.00, 90, 10, 'Chaussures de sport obligatoires.', TRUE, 4),
('Randonnée guidée #085', 'Parcours en extérieur accompagné par un guide.', 15.00, 150, 6, 'Chaussures de marche et bouteille d’eau.', TRUE, 5),
('Session paintball #086', 'Partie de paintball encadrée avec équipement fourni.', 35.00, 120, 14, 'Équipement de protection fourni.', TRUE, 6),
('Cours de danse #087', 'Cours collectif adapté au niveau des participants.', 20.00, 75, 6, 'Tenue souple et chaussures adaptées.', TRUE, 7),
('Balade à vélo #088', 'Sortie à vélo avec itinéraire préparé.', 22.00, 120, 6, 'Casque fourni. Tenue sportive conseillée.', TRUE, 8),
('Atelier créatif #089', 'Atelier manuel avec matériel mis à disposition.', 16.00, 90, 6, 'Matériel fourni sur place.', TRUE, 9),
('Séance de remise en forme #090', 'Séance sportive collective avec accompagnement.', 24.00, 60, 6, 'Tenue sportive et bouteille d’eau.', TRUE, 10),
('Cours de yoga #091', 'Séance de yoga accessible aux débutants.', 18.00, 60, 6, 'Tenue confortable et tapis conseillé.', TRUE, 11),
('Escape game #092', 'Jeu immersif en équipe avec énigmes.', 32.00, 90, 12, 'Aucun matériel nécessaire.', TRUE, 12),
('Atelier cuisine #093', 'Préparation guidée d’une recette et dégustation.', 42.00, 120, 6, 'Tablier conseillé.', TRUE, 13),
('Initiation escalade #094', 'Découverte de l’escalade avec encadrement.', 28.00, 90, 10, 'Chaussures de sport obligatoires.', TRUE, 14),
('Randonnée guidée #095', 'Parcours en extérieur accompagné par un guide.', 15.00, 150, 6, 'Chaussures de marche et bouteille d’eau.', TRUE, 15),
('Session paintball #096', 'Partie de paintball encadrée avec équipement fourni.', 35.00, 120, 14, 'Équipement de protection fourni.', TRUE, 16),
('Cours de danse #097', 'Cours collectif adapté au niveau des participants.', 20.00, 75, 6, 'Tenue souple et chaussures adaptées.', TRUE, 17),
('Balade à vélo #098', 'Sortie à vélo avec itinéraire préparé.', 22.00, 120, 6, 'Casque fourni. Tenue sportive conseillée.', TRUE, 18),
('Atelier créatif #099', 'Atelier manuel avec matériel mis à disposition.', 16.00, 90, 6, 'Matériel fourni sur place.', TRUE, 19),
('Séance de remise en forme #100', 'Séance sportive collective avec accompagnement.', 24.00, 60, 6, 'Tenue sportive et bouteille d’eau.', TRUE, 20);