INSERT INTO activity_location (
    id, partner_id, name, street, house_number, box,
    city, postal_code, country, latitude, longitude,
    access_information, active
) VALUES
(1, 1, 'Studio Loi', 'Rue de la Loi', '11', NULL, 'Bruxelles', '1000', 'Belgique', NULL, NULL, 'Entrée par la porte principale. Se présenter 10 minutes avant le début.', TRUE),
(2, 2, 'Espace Louise', 'Avenue Louise', '12', NULL, 'Ixelles', '1050', 'Belgique', NULL, NULL, 'Sonner à l’interphone au nom de l’établissement. Vestiaires au sous-sol.', TRUE),
(3, 3, 'Atelier Charleroi', 'Chaussée de Charleroi', '13', NULL, 'Saint-Gilles', '1060', 'Belgique', NULL, NULL, 'Parking gratuit devant le bâtiment. Accueil au rez-de-chaussée.', TRUE),
(4, 4, 'Salle Neuve', 'Rue Neuve', '14', NULL, 'Bruxelles', '1000', 'Belgique', NULL, NULL, 'Accessible en métro et en tram. Rendez-vous à l’accueil du premier étage.', TRUE),
(5, 5, 'Point de départ Guillemins', 'Rue des Guillemins', '15', NULL, 'Liège', '4000', 'Belgique', NULL, NULL, 'Accès par la cour intérieure. Un membre de l’équipe attend les participants.', TRUE),
(6, 6, 'Terrain Korenmarkt', 'Korenmarkt', '16', NULL, 'Gent', '9000', 'Belgique', NULL, NULL, 'Emplacements vélos disponibles. Se présenter au comptoir d’accueil.', TRUE),
(7, 7, 'Salle Meir', 'Meir', '17', NULL, 'Antwerpen', '2000', 'Belgique', NULL, NULL, 'Bâtiment accessible aux personnes à mobilité réduite. Ascenseur à droite de l’entrée.', TRUE),
(8, 8, 'Atelier Fer', 'Rue de Fer', '18', NULL, 'Namur', '5000', 'Belgique', NULL, NULL, 'Rendez-vous sur le parking à l’entrée du site, 15 minutes avant l’heure.', TRUE),
(9, 9, 'Point de départ Bondgenotenlaan', 'Bondgenotenlaan', '19', NULL, 'Leuven', '3000', 'Belgique', NULL, NULL, 'Entrée par la porte principale. Se présenter 10 minutes avant le début.', TRUE),
(10, 10, 'Centre aquatique Tirou', 'Boulevard Tirou', '20', NULL, 'Charleroi', '6000', 'Belgique', NULL, NULL, 'Sonner à l’interphone au nom de l’établissement. Vestiaires au sous-sol.', TRUE),
(11, 11, 'Studio Sablon', 'Rue du Sablon', '21', NULL, 'Bruxelles', '1000', 'Belgique', NULL, NULL, 'Parking gratuit devant le bâtiment. Accueil au rez-de-chaussée.', TRUE),
(12, 12, 'Parc Stationsstraat', 'Stationsstraat', '22', NULL, 'Mechelen', '2800', 'Belgique', NULL, NULL, 'Accessible en métro et en tram. Rendez-vous à l’accueil du premier étage.', TRUE),
(13, 13, 'Studio Mons', 'Rue de Mons', '23', NULL, 'Nivelles', '1400', 'Belgique', NULL, NULL, 'Accès par la cour intérieure. Un membre de l’équipe attend les participants.', TRUE),
(14, 14, 'Base nautique Zeedijk', 'Zeedijk', '24', NULL, 'Oostende', '8400', 'Belgique', NULL, NULL, 'Emplacements vélos disponibles. Se présenter au comptoir d’accueil.', TRUE),
(15, 15, 'Atelier Grand-Place', 'Grand-Place', '25', NULL, 'Mons', '7000', 'Belgique', NULL, NULL, 'Bâtiment accessible aux personnes à mobilité réduite. Ascenseur à droite de l’entrée.', TRUE),
(16, 16, 'Point de départ Royale', 'Rue Royale', '26', NULL, 'Bruxelles', '1000', 'Belgique', NULL, NULL, 'Rendez-vous sur le parking à l’entrée du site, 15 minutes avant l’heure.', TRUE),
(17, 17, 'Point de rendez-vous Sint-Pietersnieuwstraat', 'Sint-Pietersnieuwstraat', '27', NULL, 'Gent', '9000', 'Belgique', NULL, NULL, 'Entrée par la porte principale. Se présenter 10 minutes avant le début.', TRUE),
(18, 18, 'Centre équestre Saint-Gilles', 'Rue Saint-Gilles', '28', NULL, 'Liège', '4000', 'Belgique', NULL, NULL, 'Sonner à l’interphone au nom de l’établissement. Vestiaires au sous-sol.', TRUE),
(19, 19, 'Complexe Turnhoutsebaan', 'Turnhoutsebaan', '29', NULL, 'Antwerpen', '2140', 'Belgique', NULL, NULL, 'Parking gratuit devant le bâtiment. Accueil au rez-de-chaussée.', TRUE),
(20, 20, 'Salle Namur', 'Rue de Namur', '30', NULL, 'Wavre', '1300', 'Belgique', NULL, NULL, 'Accessible en métro et en tram. Rendez-vous à l’accueil du premier étage.', TRUE),
(21, 21, 'Studio Waterloo', 'Chaussée de Waterloo', '31', NULL, 'Uccle', '1180', 'Belgique', NULL, NULL, 'Accès par la cour intérieure. Un membre de l’équipe attend les participants.', TRUE),
(22, 22, 'Base nautique Kapellestraat', 'Kapellestraat', '32', NULL, 'Brugge', '8000', 'Belgique', NULL, NULL, 'Emplacements vélos disponibles. Se présenter au comptoir d’accueil.', TRUE),
(23, 23, 'Maison Bruxelles', 'Rue de Bruxelles', '33', NULL, 'Tournai', '7500', 'Belgique', NULL, NULL, 'Bâtiment accessible aux personnes à mobilité réduite. Ascenseur à droite de l’entrée.', TRUE),
(24, 24, 'Salle Tiensestraat', 'Tiensestraat', '34', NULL, 'Leuven', '3000', 'Belgique', NULL, NULL, 'Rendez-vous sur le parking à l’entrée du site, 15 minutes avant l’heure.', TRUE),
(25, 25, 'Atelier l', 'Rue de l''Ange', '35', NULL, 'Namur', '5000', 'Belgique', NULL, NULL, 'Entrée par la porte principale. Se présenter 10 minutes avant le début.', TRUE),
(26, 26, 'Point de départ Veldstraat', 'Veldstraat', '36', NULL, 'Gent', '9000', 'Belgique', NULL, NULL, 'Sonner à l’interphone au nom de l’établissement. Vestiaires au sous-sol.', TRUE),
(27, 27, 'Studio Commerce', 'Rue du Commerce', '37', NULL, 'Bruxelles', '1000', 'Belgique', NULL, NULL, 'Parking gratuit devant le bâtiment. Accueil au rez-de-chaussée.', TRUE),
(28, 28, 'Skatepark Hasseltsestraat', 'Hasseltsestraat', '38', NULL, 'Genk', '3600', 'Belgique', NULL, NULL, 'Accessible en métro et en tram. Rendez-vous à l’accueil du premier étage.', TRUE),
(29, 29, 'Jardin Léopold', 'Rue Léopold', '39', NULL, 'Liège', '4000', 'Belgique', NULL, NULL, 'Accès par la cour intérieure. Un membre de l’équipe attend les participants.', TRUE),
(30, 30, 'Terrain Groenplaats', 'Groenplaats', '40', NULL, 'Antwerpen', '2000', 'Belgique', NULL, NULL, 'Emplacements vélos disponibles. Se présenter au comptoir d’accueil.', TRUE),
(31, 31, 'Atelier Arts', 'Avenue des Arts', '41', NULL, 'Bruxelles', '1000', 'Belgique', NULL, NULL, 'Bâtiment accessible aux personnes à mobilité réduite. Ascenseur à droite de l’entrée.', TRUE),
(32, 32, 'Club nautique Nieuwstraat', 'Nieuwstraat', '42', NULL, 'Kortrijk', '8500', 'Belgique', NULL, NULL, 'Rendez-vous sur le parking à l’entrée du site, 15 minutes avant l’heure.', TRUE),
(33, 33, 'Studio Station', 'Rue de la Station', '43', NULL, 'Ottignies', '1340', 'Belgique', NULL, NULL, 'Entrée par la porte principale. Se présenter 10 minutes avant le début.', TRUE),
(34, 34, 'Salle Markt', 'Markt', '44', NULL, 'Hasselt', '3500', 'Belgique', NULL, NULL, 'Sonner à l’interphone au nom de l’établissement. Vestiaires au sous-sol.', TRUE),
(35, 35, 'Atelier l', 'Rue de l''Église', '45', NULL, 'Arlon', '6700', 'Belgique', NULL, NULL, 'Parking gratuit devant le bâtiment. Accueil au rez-de-chaussée.', TRUE),
(36, 36, 'Practice Haute', 'Rue Haute', '46', NULL, 'Bruxelles', '1000', 'Belgique', NULL, NULL, 'Accessible en métro et en tram. Rendez-vous à l’accueil du premier étage.', TRUE),
(37, 37, 'Espace Steenweg', 'Steenweg', '47', NULL, 'Vilvoorde', '1800', 'Belgique', NULL, NULL, 'Accès par la cour intérieure. Un membre de l’équipe attend les participants.', TRUE),
(38, 38, 'Point de rendez-vous l', 'Rue de l''Université', '48', NULL, 'Liège', '4000', 'Belgique', NULL, NULL, 'Emplacements vélos disponibles. Se présenter au comptoir d’accueil.', TRUE),
(39, 39, 'Atelier Brabantdam', 'Brabantdam', '49', NULL, 'Gent', '9000', 'Belgique', NULL, NULL, 'Bâtiment accessible aux personnes à mobilité réduite. Ascenseur à droite de l’entrée.', TRUE),
(40, 40, 'Base outdoor Carmes', 'Rue des Carmes', '50', NULL, 'Namur', '5000', 'Belgique', NULL, NULL, 'Rendez-vous sur le parking à l’entrée du site, 15 minutes avant l’heure.', TRUE),
(41, 1, 'Studio Loi', 'Rue de la Loi', '51', NULL, 'Bruxelles', '1000', 'Belgique', NULL, NULL, 'Entrée par la porte principale. Se présenter 10 minutes avant le début.', TRUE),
(42, 2, 'Espace Louise', 'Avenue Louise', '52', NULL, 'Ixelles', '1050', 'Belgique', NULL, NULL, 'Sonner à l’interphone au nom de l’établissement. Vestiaires au sous-sol.', TRUE),
(43, 3, 'Atelier Charleroi', 'Chaussée de Charleroi', '53', NULL, 'Saint-Gilles', '1060', 'Belgique', NULL, NULL, 'Parking gratuit devant le bâtiment. Accueil au rez-de-chaussée.', TRUE),
(44, 4, 'Salle Neuve', 'Rue Neuve', '54', NULL, 'Bruxelles', '1000', 'Belgique', NULL, NULL, 'Accessible en métro et en tram. Rendez-vous à l’accueil du premier étage.', TRUE),
(45, 5, 'Point de départ Guillemins', 'Rue des Guillemins', '55', NULL, 'Liège', '4000', 'Belgique', NULL, NULL, 'Accès par la cour intérieure. Un membre de l’équipe attend les participants.', TRUE),
(46, 6, 'Terrain Korenmarkt', 'Korenmarkt', '56', NULL, 'Gent', '9000', 'Belgique', NULL, NULL, 'Emplacements vélos disponibles. Se présenter au comptoir d’accueil.', TRUE),
(47, 7, 'Salle Meir', 'Meir', '57', NULL, 'Antwerpen', '2000', 'Belgique', NULL, NULL, 'Bâtiment accessible aux personnes à mobilité réduite. Ascenseur à droite de l’entrée.', TRUE),
(48, 8, 'Atelier Fer', 'Rue de Fer', '58', NULL, 'Namur', '5000', 'Belgique', NULL, NULL, 'Rendez-vous sur le parking à l’entrée du site, 15 minutes avant l’heure.', TRUE),
(49, 9, 'Point de départ Bondgenotenlaan', 'Bondgenotenlaan', '59', NULL, 'Leuven', '3000', 'Belgique', NULL, NULL, 'Entrée par la porte principale. Se présenter 10 minutes avant le début.', TRUE),
(50, 10, 'Centre aquatique Tirou', 'Boulevard Tirou', '60', NULL, 'Charleroi', '6000', 'Belgique', NULL, NULL, 'Sonner à l’interphone au nom de l’établissement. Vestiaires au sous-sol.', TRUE),
(51, 11, 'Studio Sablon', 'Rue du Sablon', '61', NULL, 'Bruxelles', '1000', 'Belgique', NULL, NULL, 'Parking gratuit devant le bâtiment. Accueil au rez-de-chaussée.', TRUE),
(52, 12, 'Parc Stationsstraat', 'Stationsstraat', '62', NULL, 'Mechelen', '2800', 'Belgique', NULL, NULL, 'Accessible en métro et en tram. Rendez-vous à l’accueil du premier étage.', TRUE),
(53, 13, 'Studio Mons', 'Rue de Mons', '63', NULL, 'Nivelles', '1400', 'Belgique', NULL, NULL, 'Accès par la cour intérieure. Un membre de l’équipe attend les participants.', TRUE),
(54, 14, 'Base nautique Zeedijk', 'Zeedijk', '64', NULL, 'Oostende', '8400', 'Belgique', NULL, NULL, 'Emplacements vélos disponibles. Se présenter au comptoir d’accueil.', TRUE),
(55, 15, 'Atelier Grand-Place', 'Grand-Place', '65', NULL, 'Mons', '7000', 'Belgique', NULL, NULL, 'Bâtiment accessible aux personnes à mobilité réduite. Ascenseur à droite de l’entrée.', TRUE),
(56, 16, 'Point de départ Royale', 'Rue Royale', '66', NULL, 'Bruxelles', '1000', 'Belgique', NULL, NULL, 'Rendez-vous sur le parking à l’entrée du site, 15 minutes avant l’heure.', TRUE),
(57, 17, 'Point de rendez-vous Sint-Pietersnieuwstraat', 'Sint-Pietersnieuwstraat', '67', NULL, 'Gent', '9000', 'Belgique', NULL, NULL, 'Entrée par la porte principale. Se présenter 10 minutes avant le début.', TRUE),
(58, 18, 'Centre équestre Saint-Gilles', 'Rue Saint-Gilles', '68', NULL, 'Liège', '4000', 'Belgique', NULL, NULL, 'Sonner à l’interphone au nom de l’établissement. Vestiaires au sous-sol.', TRUE),
(59, 19, 'Complexe Turnhoutsebaan', 'Turnhoutsebaan', '69', NULL, 'Antwerpen', '2140', 'Belgique', NULL, NULL, 'Parking gratuit devant le bâtiment. Accueil au rez-de-chaussée.', TRUE),
(60, 20, 'Salle Namur', 'Rue de Namur', '70', NULL, 'Wavre', '1300', 'Belgique', NULL, NULL, 'Accessible en métro et en tram. Rendez-vous à l’accueil du premier étage.', TRUE),
(61, 21, 'Studio Waterloo', 'Chaussée de Waterloo', '71', NULL, 'Uccle', '1180', 'Belgique', NULL, NULL, 'Accès par la cour intérieure. Un membre de l’équipe attend les participants.', TRUE),
(62, 22, 'Base nautique Kapellestraat', 'Kapellestraat', '72', NULL, 'Brugge', '8000', 'Belgique', NULL, NULL, 'Emplacements vélos disponibles. Se présenter au comptoir d’accueil.', TRUE),
(63, 23, 'Maison Bruxelles', 'Rue de Bruxelles', '73', NULL, 'Tournai', '7500', 'Belgique', NULL, NULL, 'Bâtiment accessible aux personnes à mobilité réduite. Ascenseur à droite de l’entrée.', TRUE),
(64, 24, 'Salle Tiensestraat', 'Tiensestraat', '74', NULL, 'Leuven', '3000', 'Belgique', NULL, NULL, 'Rendez-vous sur le parking à l’entrée du site, 15 minutes avant l’heure.', TRUE),
(65, 25, 'Atelier l', 'Rue de l''Ange', '75', NULL, 'Namur', '5000', 'Belgique', NULL, NULL, 'Entrée par la porte principale. Se présenter 10 minutes avant le début.', TRUE),
(66, 26, 'Point de départ Veldstraat', 'Veldstraat', '76', NULL, 'Gent', '9000', 'Belgique', NULL, NULL, 'Sonner à l’interphone au nom de l’établissement. Vestiaires au sous-sol.', TRUE),
(67, 27, 'Studio Commerce', 'Rue du Commerce', '77', NULL, 'Bruxelles', '1000', 'Belgique', NULL, NULL, 'Parking gratuit devant le bâtiment. Accueil au rez-de-chaussée.', TRUE),
(68, 28, 'Skatepark Hasseltsestraat', 'Hasseltsestraat', '78', NULL, 'Genk', '3600', 'Belgique', NULL, NULL, 'Accessible en métro et en tram. Rendez-vous à l’accueil du premier étage.', TRUE),
(69, 29, 'Jardin Léopold', 'Rue Léopold', '79', NULL, 'Liège', '4000', 'Belgique', NULL, NULL, 'Accès par la cour intérieure. Un membre de l’équipe attend les participants.', TRUE),
(70, 30, 'Terrain Groenplaats', 'Groenplaats', '80', NULL, 'Antwerpen', '2000', 'Belgique', NULL, NULL, 'Emplacements vélos disponibles. Se présenter au comptoir d’accueil.', TRUE),
(71, 31, 'Atelier Arts', 'Avenue des Arts', '81', NULL, 'Bruxelles', '1000', 'Belgique', NULL, NULL, 'Bâtiment accessible aux personnes à mobilité réduite. Ascenseur à droite de l’entrée.', TRUE),
(72, 32, 'Club nautique Nieuwstraat', 'Nieuwstraat', '82', NULL, 'Kortrijk', '8500', 'Belgique', NULL, NULL, 'Rendez-vous sur le parking à l’entrée du site, 15 minutes avant l’heure.', TRUE),
(73, 33, 'Studio Station', 'Rue de la Station', '83', NULL, 'Ottignies', '1340', 'Belgique', NULL, NULL, 'Entrée par la porte principale. Se présenter 10 minutes avant le début.', TRUE),
(74, 34, 'Salle Markt', 'Markt', '84', NULL, 'Hasselt', '3500', 'Belgique', NULL, NULL, 'Sonner à l’interphone au nom de l’établissement. Vestiaires au sous-sol.', TRUE),
(75, 35, 'Atelier l', 'Rue de l''Église', '85', NULL, 'Arlon', '6700', 'Belgique', NULL, NULL, 'Parking gratuit devant le bâtiment. Accueil au rez-de-chaussée.', TRUE),
(76, 36, 'Practice Haute', 'Rue Haute', '86', NULL, 'Bruxelles', '1000', 'Belgique', NULL, NULL, 'Accessible en métro et en tram. Rendez-vous à l’accueil du premier étage.', TRUE),
(77, 37, 'Espace Steenweg', 'Steenweg', '87', NULL, 'Vilvoorde', '1800', 'Belgique', NULL, NULL, 'Accès par la cour intérieure. Un membre de l’équipe attend les participants.', TRUE),
(78, 38, 'Point de rendez-vous l', 'Rue de l''Université', '88', NULL, 'Liège', '4000', 'Belgique', NULL, NULL, 'Emplacements vélos disponibles. Se présenter au comptoir d’accueil.', TRUE),
(79, 39, 'Atelier Brabantdam', 'Brabantdam', '89', NULL, 'Gent', '9000', 'Belgique', NULL, NULL, 'Bâtiment accessible aux personnes à mobilité réduite. Ascenseur à droite de l’entrée.', TRUE),
(80, 40, 'Base outdoor Carmes', 'Rue des Carmes', '90', NULL, 'Namur', '5000', 'Belgique', NULL, NULL, 'Rendez-vous sur le parking à l’entrée du site, 15 minutes avant l’heure.', TRUE),
(81, 1, 'Studio Loi', 'Rue de la Loi', '91', NULL, 'Bruxelles', '1000', 'Belgique', NULL, NULL, 'Entrée par la porte principale. Se présenter 10 minutes avant le début.', TRUE),
(82, 2, 'Espace Louise', 'Avenue Louise', '92', NULL, 'Ixelles', '1050', 'Belgique', NULL, NULL, 'Sonner à l’interphone au nom de l’établissement. Vestiaires au sous-sol.', TRUE),
(83, 3, 'Atelier Charleroi', 'Chaussée de Charleroi', '93', NULL, 'Saint-Gilles', '1060', 'Belgique', NULL, NULL, 'Parking gratuit devant le bâtiment. Accueil au rez-de-chaussée.', TRUE),
(84, 4, 'Salle Neuve', 'Rue Neuve', '94', NULL, 'Bruxelles', '1000', 'Belgique', NULL, NULL, 'Accessible en métro et en tram. Rendez-vous à l’accueil du premier étage.', TRUE),
(85, 5, 'Point de départ Guillemins', 'Rue des Guillemins', '95', NULL, 'Liège', '4000', 'Belgique', NULL, NULL, 'Accès par la cour intérieure. Un membre de l’équipe attend les participants.', TRUE),
(86, 6, 'Terrain Korenmarkt', 'Korenmarkt', '96', NULL, 'Gent', '9000', 'Belgique', NULL, NULL, 'Emplacements vélos disponibles. Se présenter au comptoir d’accueil.', TRUE),
(87, 7, 'Salle Meir', 'Meir', '97', NULL, 'Antwerpen', '2000', 'Belgique', NULL, NULL, 'Bâtiment accessible aux personnes à mobilité réduite. Ascenseur à droite de l’entrée.', TRUE),
(88, 8, 'Atelier Fer', 'Rue de Fer', '98', NULL, 'Namur', '5000', 'Belgique', NULL, NULL, 'Rendez-vous sur le parking à l’entrée du site, 15 minutes avant l’heure.', TRUE),
(89, 9, 'Point de départ Bondgenotenlaan', 'Bondgenotenlaan', '99', NULL, 'Leuven', '3000', 'Belgique', NULL, NULL, 'Entrée par la porte principale. Se présenter 10 minutes avant le début.', TRUE),
(90, 10, 'Centre aquatique Tirou', 'Boulevard Tirou', '100', NULL, 'Charleroi', '6000', 'Belgique', NULL, NULL, 'Sonner à l’interphone au nom de l’établissement. Vestiaires au sous-sol.', TRUE),
(91, 11, 'Studio Sablon', 'Rue du Sablon', '101', NULL, 'Bruxelles', '1000', 'Belgique', NULL, NULL, 'Parking gratuit devant le bâtiment. Accueil au rez-de-chaussée.', TRUE),
(92, 12, 'Parc Stationsstraat', 'Stationsstraat', '102', NULL, 'Mechelen', '2800', 'Belgique', NULL, NULL, 'Accessible en métro et en tram. Rendez-vous à l’accueil du premier étage.', TRUE),
(93, 13, 'Studio Mons', 'Rue de Mons', '103', NULL, 'Nivelles', '1400', 'Belgique', NULL, NULL, 'Accès par la cour intérieure. Un membre de l’équipe attend les participants.', TRUE),
(94, 14, 'Base nautique Zeedijk', 'Zeedijk', '104', NULL, 'Oostende', '8400', 'Belgique', NULL, NULL, 'Emplacements vélos disponibles. Se présenter au comptoir d’accueil.', TRUE),
(95, 15, 'Atelier Grand-Place', 'Grand-Place', '105', NULL, 'Mons', '7000', 'Belgique', NULL, NULL, 'Bâtiment accessible aux personnes à mobilité réduite. Ascenseur à droite de l’entrée.', TRUE),
(96, 16, 'Point de départ Royale', 'Rue Royale', '106', NULL, 'Bruxelles', '1000', 'Belgique', NULL, NULL, 'Rendez-vous sur le parking à l’entrée du site, 15 minutes avant l’heure.', TRUE),
(97, 17, 'Point de rendez-vous Sint-Pietersnieuwstraat', 'Sint-Pietersnieuwstraat', '107', NULL, 'Gent', '9000', 'Belgique', NULL, NULL, 'Entrée par la porte principale. Se présenter 10 minutes avant le début.', TRUE),
(98, 18, 'Centre équestre Saint-Gilles', 'Rue Saint-Gilles', '108', NULL, 'Liège', '4000', 'Belgique', NULL, NULL, 'Sonner à l’interphone au nom de l’établissement. Vestiaires au sous-sol.', TRUE),
(99, 19, 'Complexe Turnhoutsebaan', 'Turnhoutsebaan', '109', NULL, 'Antwerpen', '2140', 'Belgique', NULL, NULL, 'Parking gratuit devant le bâtiment. Accueil au rez-de-chaussée.', TRUE),
(100, 20, 'Salle Namur', 'Rue de Namur', '110', NULL, 'Wavre', '1300', 'Belgique', NULL, NULL, 'Accueil sur place. Se présenter 10 minutes avant le début.', TRUE);