INSERT INTO activity_location (
    id, partner_id, name, street, house_number, box,
    city, postal_code, country, latitude, longitude,
    access_information, active
) VALUES
(1, 1, 'Lieu activité #001', 'Rue de la Loi', '11', NULL, 'Bruxelles', '1000', 'Belgique', NULL, NULL, 'Accueil sur place. Se présenter 10 minutes avant le début.', TRUE),
(2, 2, 'Lieu activité #002', 'Avenue Louise', '12', NULL, 'Ixelles', '1050', 'Belgique', NULL, NULL, 'Accueil sur place. Se présenter 10 minutes avant le début.', TRUE),
(3, 3, 'Lieu activité #003', 'Chaussée de Charleroi', '13', NULL, 'Saint-Gilles', '1060', 'Belgique', NULL, NULL, 'Accueil sur place. Se présenter 10 minutes avant le début.', TRUE),
(4, 4, 'Lieu activité #004', 'Rue Neuve', '14', NULL, 'Bruxelles', '1000', 'Belgique', NULL, NULL, 'Accueil sur place. Se présenter 10 minutes avant le début.', TRUE),
(5, 5, 'Lieu activité #005', 'Rue des Guillemins', '15', NULL, 'Liège', '4000', 'Belgique', NULL, NULL, 'Accueil sur place. Se présenter 10 minutes avant le début.', TRUE),
(6, 6, 'Lieu activité #006', 'Korenmarkt', '16', NULL, 'Gent', '9000', 'Belgique', NULL, NULL, 'Accueil sur place. Se présenter 10 minutes avant le début.', TRUE),
(7, 7, 'Lieu activité #007', 'Meir', '17', NULL, 'Antwerpen', '2000', 'Belgique', NULL, NULL, 'Accueil sur place. Se présenter 10 minutes avant le début.', TRUE),
(8, 8, 'Lieu activité #008', 'Rue de Fer', '18', NULL, 'Namur', '5000', 'Belgique', NULL, NULL, 'Accueil sur place. Se présenter 10 minutes avant le début.', TRUE),
(9, 9, 'Lieu activité #009', 'Bondgenotenlaan', '19', NULL, 'Leuven', '3000', 'Belgique', NULL, NULL, 'Accueil sur place. Se présenter 10 minutes avant le début.', TRUE),
(10, 10, 'Lieu activité #010', 'Boulevard Tirou', '20', NULL, 'Charleroi', '6000', 'Belgique', NULL, NULL, 'Accueil sur place. Se présenter 10 minutes avant le début.', TRUE),
(11, 11, 'Lieu activité #011', 'Rue du Sablon', '21', NULL, 'Bruxelles', '1000', 'Belgique', NULL, NULL, 'Accueil sur place. Se présenter 10 minutes avant le début.', TRUE),
(12, 12, 'Lieu activité #012', 'Stationsstraat', '22', NULL, 'Mechelen', '2800', 'Belgique', NULL, NULL, 'Accueil sur place. Se présenter 10 minutes avant le début.', TRUE),
(13, 13, 'Lieu activité #013', 'Rue de Mons', '23', NULL, 'Nivelles', '1400', 'Belgique', NULL, NULL, 'Accueil sur place. Se présenter 10 minutes avant le début.', TRUE),
(14, 14, 'Lieu activité #014', 'Zeedijk', '24', NULL, 'Oostende', '8400', 'Belgique', NULL, NULL, 'Accueil sur place. Se présenter 10 minutes avant le début.', TRUE),
(15, 15, 'Lieu activité #015', 'Grand-Place', '25', NULL, 'Mons', '7000', 'Belgique', NULL, NULL, 'Accueil sur place. Se présenter 10 minutes avant le début.', TRUE),
(16, 16, 'Lieu activité #016', 'Rue Royale', '26', NULL, 'Bruxelles', '1000', 'Belgique', NULL, NULL, 'Accueil sur place. Se présenter 10 minutes avant le début.', TRUE),
(17, 17, 'Lieu activité #017', 'Sint-Pietersnieuwstraat', '27', NULL, 'Gent', '9000', 'Belgique', NULL, NULL, 'Accueil sur place. Se présenter 10 minutes avant le début.', TRUE),
(18, 18, 'Lieu activité #018', 'Rue Saint-Gilles', '28', NULL, 'Liège', '4000', 'Belgique', NULL, NULL, 'Accueil sur place. Se présenter 10 minutes avant le début.', TRUE),
(19, 19, 'Lieu activité #019', 'Turnhoutsebaan', '29', NULL, 'Antwerpen', '2140', 'Belgique', NULL, NULL, 'Accueil sur place. Se présenter 10 minutes avant le début.', TRUE),
(20, 20, 'Lieu activité #020', 'Rue de Namur', '30', NULL, 'Wavre', '1300', 'Belgique', NULL, NULL, 'Accueil sur place. Se présenter 10 minutes avant le début.', TRUE),
(21, 21, 'Lieu activité #021', 'Chaussée de Waterloo', '31', NULL, 'Uccle', '1180', 'Belgique', NULL, NULL, 'Accueil sur place. Se présenter 10 minutes avant le début.', TRUE),
(22, 22, 'Lieu activité #022', 'Kapellestraat', '32', NULL, 'Brugge', '8000', 'Belgique', NULL, NULL, 'Accueil sur place. Se présenter 10 minutes avant le début.', TRUE),
(23, 23, 'Lieu activité #023', 'Rue de Bruxelles', '33', NULL, 'Tournai', '7500', 'Belgique', NULL, NULL, 'Accueil sur place. Se présenter 10 minutes avant le début.', TRUE),
(24, 24, 'Lieu activité #024', 'Tiensestraat', '34', NULL, 'Leuven', '3000', 'Belgique', NULL, NULL, 'Accueil sur place. Se présenter 10 minutes avant le début.', TRUE),
(25, 25, 'Lieu activité #025', 'Rue de l''Ange', '35', NULL, 'Namur', '5000', 'Belgique', NULL, NULL, 'Accueil sur place. Se présenter 10 minutes avant le début.', TRUE),
(26, 26, 'Lieu activité #026', 'Veldstraat', '36', NULL, 'Gent', '9000', 'Belgique', NULL, NULL, 'Accueil sur place. Se présenter 10 minutes avant le début.', TRUE),
(27, 27, 'Lieu activité #027', 'Rue du Commerce', '37', NULL, 'Bruxelles', '1000', 'Belgique', NULL, NULL, 'Accueil sur place. Se présenter 10 minutes avant le début.', TRUE),
(28, 28, 'Lieu activité #028', 'Hasseltsestraat', '38', NULL, 'Genk', '3600', 'Belgique', NULL, NULL, 'Accueil sur place. Se présenter 10 minutes avant le début.', TRUE),
(29, 29, 'Lieu activité #029', 'Rue Léopold', '39', NULL, 'Liège', '4000', 'Belgique', NULL, NULL, 'Accueil sur place. Se présenter 10 minutes avant le début.', TRUE),
(30, 30, 'Lieu activité #030', 'Groenplaats', '40', NULL, 'Antwerpen', '2000', 'Belgique', NULL, NULL, 'Accueil sur place. Se présenter 10 minutes avant le début.', TRUE),
(31, 31, 'Lieu activité #031', 'Avenue des Arts', '41', NULL, 'Bruxelles', '1000', 'Belgique', NULL, NULL, 'Accueil sur place. Se présenter 10 minutes avant le début.', TRUE),
(32, 32, 'Lieu activité #032', 'Nieuwstraat', '42', NULL, 'Kortrijk', '8500', 'Belgique', NULL, NULL, 'Accueil sur place. Se présenter 10 minutes avant le début.', TRUE),
(33, 33, 'Lieu activité #033', 'Rue de la Station', '43', NULL, 'Ottignies', '1340', 'Belgique', NULL, NULL, 'Accueil sur place. Se présenter 10 minutes avant le début.', TRUE),
(34, 34, 'Lieu activité #034', 'Markt', '44', NULL, 'Hasselt', '3500', 'Belgique', NULL, NULL, 'Accueil sur place. Se présenter 10 minutes avant le début.', TRUE),
(35, 35, 'Lieu activité #035', 'Rue de l''Église', '45', NULL, 'Arlon', '6700', 'Belgique', NULL, NULL, 'Accueil sur place. Se présenter 10 minutes avant le début.', TRUE),
(36, 36, 'Lieu activité #036', 'Rue Haute', '46', NULL, 'Bruxelles', '1000', 'Belgique', NULL, NULL, 'Accueil sur place. Se présenter 10 minutes avant le début.', TRUE),
(37, 37, 'Lieu activité #037', 'Steenweg', '47', NULL, 'Vilvoorde', '1800', 'Belgique', NULL, NULL, 'Accueil sur place. Se présenter 10 minutes avant le début.', TRUE),
(38, 38, 'Lieu activité #038', 'Rue de l''Université', '48', NULL, 'Liège', '4000', 'Belgique', NULL, NULL, 'Accueil sur place. Se présenter 10 minutes avant le début.', TRUE),
(39, 39, 'Lieu activité #039', 'Brabantdam', '49', NULL, 'Gent', '9000', 'Belgique', NULL, NULL, 'Accueil sur place. Se présenter 10 minutes avant le début.', TRUE),
(40, 40, 'Lieu activité #040', 'Rue des Carmes', '50', NULL, 'Namur', '5000', 'Belgique', NULL, NULL, 'Accueil sur place. Se présenter 10 minutes avant le début.', TRUE),
(41, 1, 'Lieu activité #041', 'Rue de la Loi', '51', NULL, 'Bruxelles', '1000', 'Belgique', NULL, NULL, 'Accueil sur place. Se présenter 10 minutes avant le début.', TRUE),
(42, 2, 'Lieu activité #042', 'Avenue Louise', '52', NULL, 'Ixelles', '1050', 'Belgique', NULL, NULL, 'Accueil sur place. Se présenter 10 minutes avant le début.', TRUE),
(43, 3, 'Lieu activité #043', 'Chaussée de Charleroi', '53', NULL, 'Saint-Gilles', '1060', 'Belgique', NULL, NULL, 'Accueil sur place. Se présenter 10 minutes avant le début.', TRUE),
(44, 4, 'Lieu activité #044', 'Rue Neuve', '54', NULL, 'Bruxelles', '1000', 'Belgique', NULL, NULL, 'Accueil sur place. Se présenter 10 minutes avant le début.', TRUE),
(45, 5, 'Lieu activité #045', 'Rue des Guillemins', '55', NULL, 'Liège', '4000', 'Belgique', NULL, NULL, 'Accueil sur place. Se présenter 10 minutes avant le début.', TRUE),
(46, 6, 'Lieu activité #046', 'Korenmarkt', '56', NULL, 'Gent', '9000', 'Belgique', NULL, NULL, 'Accueil sur place. Se présenter 10 minutes avant le début.', TRUE),
(47, 7, 'Lieu activité #047', 'Meir', '57', NULL, 'Antwerpen', '2000', 'Belgique', NULL, NULL, 'Accueil sur place. Se présenter 10 minutes avant le début.', TRUE),
(48, 8, 'Lieu activité #048', 'Rue de Fer', '58', NULL, 'Namur', '5000', 'Belgique', NULL, NULL, 'Accueil sur place. Se présenter 10 minutes avant le début.', TRUE),
(49, 9, 'Lieu activité #049', 'Bondgenotenlaan', '59', NULL, 'Leuven', '3000', 'Belgique', NULL, NULL, 'Accueil sur place. Se présenter 10 minutes avant le début.', TRUE),
(50, 10, 'Lieu activité #050', 'Boulevard Tirou', '60', NULL, 'Charleroi', '6000', 'Belgique', NULL, NULL, 'Accueil sur place. Se présenter 10 minutes avant le début.', TRUE),
(51, 11, 'Lieu activité #051', 'Rue du Sablon', '61', NULL, 'Bruxelles', '1000', 'Belgique', NULL, NULL, 'Accueil sur place. Se présenter 10 minutes avant le début.', TRUE),
(52, 12, 'Lieu activité #052', 'Stationsstraat', '62', NULL, 'Mechelen', '2800', 'Belgique', NULL, NULL, 'Accueil sur place. Se présenter 10 minutes avant le début.', TRUE),
(53, 13, 'Lieu activité #053', 'Rue de Mons', '63', NULL, 'Nivelles', '1400', 'Belgique', NULL, NULL, 'Accueil sur place. Se présenter 10 minutes avant le début.', TRUE),
(54, 14, 'Lieu activité #054', 'Zeedijk', '64', NULL, 'Oostende', '8400', 'Belgique', NULL, NULL, 'Accueil sur place. Se présenter 10 minutes avant le début.', TRUE),
(55, 15, 'Lieu activité #055', 'Grand-Place', '65', NULL, 'Mons', '7000', 'Belgique', NULL, NULL, 'Accueil sur place. Se présenter 10 minutes avant le début.', TRUE),
(56, 16, 'Lieu activité #056', 'Rue Royale', '66', NULL, 'Bruxelles', '1000', 'Belgique', NULL, NULL, 'Accueil sur place. Se présenter 10 minutes avant le début.', TRUE),
(57, 17, 'Lieu activité #057', 'Sint-Pietersnieuwstraat', '67', NULL, 'Gent', '9000', 'Belgique', NULL, NULL, 'Accueil sur place. Se présenter 10 minutes avant le début.', TRUE),
(58, 18, 'Lieu activité #058', 'Rue Saint-Gilles', '68', NULL, 'Liège', '4000', 'Belgique', NULL, NULL, 'Accueil sur place. Se présenter 10 minutes avant le début.', TRUE),
(59, 19, 'Lieu activité #059', 'Turnhoutsebaan', '69', NULL, 'Antwerpen', '2140', 'Belgique', NULL, NULL, 'Accueil sur place. Se présenter 10 minutes avant le début.', TRUE),
(60, 20, 'Lieu activité #060', 'Rue de Namur', '70', NULL, 'Wavre', '1300', 'Belgique', NULL, NULL, 'Accueil sur place. Se présenter 10 minutes avant le début.', TRUE),
(61, 21, 'Lieu activité #061', 'Chaussée de Waterloo', '71', NULL, 'Uccle', '1180', 'Belgique', NULL, NULL, 'Accueil sur place. Se présenter 10 minutes avant le début.', TRUE),
(62, 22, 'Lieu activité #062', 'Kapellestraat', '72', NULL, 'Brugge', '8000', 'Belgique', NULL, NULL, 'Accueil sur place. Se présenter 10 minutes avant le début.', TRUE),
(63, 23, 'Lieu activité #063', 'Rue de Bruxelles', '73', NULL, 'Tournai', '7500', 'Belgique', NULL, NULL, 'Accueil sur place. Se présenter 10 minutes avant le début.', TRUE),
(64, 24, 'Lieu activité #064', 'Tiensestraat', '74', NULL, 'Leuven', '3000', 'Belgique', NULL, NULL, 'Accueil sur place. Se présenter 10 minutes avant le début.', TRUE),
(65, 25, 'Lieu activité #065', 'Rue de l''Ange', '75', NULL, 'Namur', '5000', 'Belgique', NULL, NULL, 'Accueil sur place. Se présenter 10 minutes avant le début.', TRUE),
(66, 26, 'Lieu activité #066', 'Veldstraat', '76', NULL, 'Gent', '9000', 'Belgique', NULL, NULL, 'Accueil sur place. Se présenter 10 minutes avant le début.', TRUE),
(67, 27, 'Lieu activité #067', 'Rue du Commerce', '77', NULL, 'Bruxelles', '1000', 'Belgique', NULL, NULL, 'Accueil sur place. Se présenter 10 minutes avant le début.', TRUE),
(68, 28, 'Lieu activité #068', 'Hasseltsestraat', '78', NULL, 'Genk', '3600', 'Belgique', NULL, NULL, 'Accueil sur place. Se présenter 10 minutes avant le début.', TRUE),
(69, 29, 'Lieu activité #069', 'Rue Léopold', '79', NULL, 'Liège', '4000', 'Belgique', NULL, NULL, 'Accueil sur place. Se présenter 10 minutes avant le début.', TRUE),
(70, 30, 'Lieu activité #070', 'Groenplaats', '80', NULL, 'Antwerpen', '2000', 'Belgique', NULL, NULL, 'Accueil sur place. Se présenter 10 minutes avant le début.', TRUE),
(71, 31, 'Lieu activité #071', 'Avenue des Arts', '81', NULL, 'Bruxelles', '1000', 'Belgique', NULL, NULL, 'Accueil sur place. Se présenter 10 minutes avant le début.', TRUE),
(72, 32, 'Lieu activité #072', 'Nieuwstraat', '82', NULL, 'Kortrijk', '8500', 'Belgique', NULL, NULL, 'Accueil sur place. Se présenter 10 minutes avant le début.', TRUE),
(73, 33, 'Lieu activité #073', 'Rue de la Station', '83', NULL, 'Ottignies', '1340', 'Belgique', NULL, NULL, 'Accueil sur place. Se présenter 10 minutes avant le début.', TRUE),
(74, 34, 'Lieu activité #074', 'Markt', '84', NULL, 'Hasselt', '3500', 'Belgique', NULL, NULL, 'Accueil sur place. Se présenter 10 minutes avant le début.', TRUE),
(75, 35, 'Lieu activité #075', 'Rue de l''Église', '85', NULL, 'Arlon', '6700', 'Belgique', NULL, NULL, 'Accueil sur place. Se présenter 10 minutes avant le début.', TRUE),
(76, 36, 'Lieu activité #076', 'Rue Haute', '86', NULL, 'Bruxelles', '1000', 'Belgique', NULL, NULL, 'Accueil sur place. Se présenter 10 minutes avant le début.', TRUE),
(77, 37, 'Lieu activité #077', 'Steenweg', '87', NULL, 'Vilvoorde', '1800', 'Belgique', NULL, NULL, 'Accueil sur place. Se présenter 10 minutes avant le début.', TRUE),
(78, 38, 'Lieu activité #078', 'Rue de l''Université', '88', NULL, 'Liège', '4000', 'Belgique', NULL, NULL, 'Accueil sur place. Se présenter 10 minutes avant le début.', TRUE),
(79, 39, 'Lieu activité #079', 'Brabantdam', '89', NULL, 'Gent', '9000', 'Belgique', NULL, NULL, 'Accueil sur place. Se présenter 10 minutes avant le début.', TRUE),
(80, 40, 'Lieu activité #080', 'Rue des Carmes', '90', NULL, 'Namur', '5000', 'Belgique', NULL, NULL, 'Accueil sur place. Se présenter 10 minutes avant le début.', TRUE),
(81, 1, 'Lieu activité #081', 'Rue de la Loi', '91', NULL, 'Bruxelles', '1000', 'Belgique', NULL, NULL, 'Accueil sur place. Se présenter 10 minutes avant le début.', TRUE),
(82, 2, 'Lieu activité #082', 'Avenue Louise', '92', NULL, 'Ixelles', '1050', 'Belgique', NULL, NULL, 'Accueil sur place. Se présenter 10 minutes avant le début.', TRUE),
(83, 3, 'Lieu activité #083', 'Chaussée de Charleroi', '93', NULL, 'Saint-Gilles', '1060', 'Belgique', NULL, NULL, 'Accueil sur place. Se présenter 10 minutes avant le début.', TRUE),
(84, 4, 'Lieu activité #084', 'Rue Neuve', '94', NULL, 'Bruxelles', '1000', 'Belgique', NULL, NULL, 'Accueil sur place. Se présenter 10 minutes avant le début.', TRUE),
(85, 5, 'Lieu activité #085', 'Rue des Guillemins', '95', NULL, 'Liège', '4000', 'Belgique', NULL, NULL, 'Accueil sur place. Se présenter 10 minutes avant le début.', TRUE),
(86, 6, 'Lieu activité #086', 'Korenmarkt', '96', NULL, 'Gent', '9000', 'Belgique', NULL, NULL, 'Accueil sur place. Se présenter 10 minutes avant le début.', TRUE),
(87, 7, 'Lieu activité #087', 'Meir', '97', NULL, 'Antwerpen', '2000', 'Belgique', NULL, NULL, 'Accueil sur place. Se présenter 10 minutes avant le début.', TRUE),
(88, 8, 'Lieu activité #088', 'Rue de Fer', '98', NULL, 'Namur', '5000', 'Belgique', NULL, NULL, 'Accueil sur place. Se présenter 10 minutes avant le début.', TRUE),
(89, 9, 'Lieu activité #089', 'Bondgenotenlaan', '99', NULL, 'Leuven', '3000', 'Belgique', NULL, NULL, 'Accueil sur place. Se présenter 10 minutes avant le début.', TRUE),
(90, 10, 'Lieu activité #090', 'Boulevard Tirou', '100', NULL, 'Charleroi', '6000', 'Belgique', NULL, NULL, 'Accueil sur place. Se présenter 10 minutes avant le début.', TRUE),
(91, 11, 'Lieu activité #091', 'Rue du Sablon', '101', NULL, 'Bruxelles', '1000', 'Belgique', NULL, NULL, 'Accueil sur place. Se présenter 10 minutes avant le début.', TRUE),
(92, 12, 'Lieu activité #092', 'Stationsstraat', '102', NULL, 'Mechelen', '2800', 'Belgique', NULL, NULL, 'Accueil sur place. Se présenter 10 minutes avant le début.', TRUE),
(93, 13, 'Lieu activité #093', 'Rue de Mons', '103', NULL, 'Nivelles', '1400', 'Belgique', NULL, NULL, 'Accueil sur place. Se présenter 10 minutes avant le début.', TRUE),
(94, 14, 'Lieu activité #094', 'Zeedijk', '104', NULL, 'Oostende', '8400', 'Belgique', NULL, NULL, 'Accueil sur place. Se présenter 10 minutes avant le début.', TRUE),
(95, 15, 'Lieu activité #095', 'Grand-Place', '105', NULL, 'Mons', '7000', 'Belgique', NULL, NULL, 'Accueil sur place. Se présenter 10 minutes avant le début.', TRUE),
(96, 16, 'Lieu activité #096', 'Rue Royale', '106', NULL, 'Bruxelles', '1000', 'Belgique', NULL, NULL, 'Accueil sur place. Se présenter 10 minutes avant le début.', TRUE),
(97, 17, 'Lieu activité #097', 'Sint-Pietersnieuwstraat', '107', NULL, 'Gent', '9000', 'Belgique', NULL, NULL, 'Accueil sur place. Se présenter 10 minutes avant le début.', TRUE),
(98, 18, 'Lieu activité #098', 'Rue Saint-Gilles', '108', NULL, 'Liège', '4000', 'Belgique', NULL, NULL, 'Accueil sur place. Se présenter 10 minutes avant le début.', TRUE),
(99, 19, 'Lieu activité #099', 'Turnhoutsebaan', '109', NULL, 'Antwerpen', '2140', 'Belgique', NULL, NULL, 'Accueil sur place. Se présenter 10 minutes avant le début.', TRUE),
(100, 20, 'Lieu activité #100', 'Rue de Namur', '110', NULL, 'Wavre', '1300', 'Belgique', NULL, NULL, 'Accueil sur place. Se présenter 10 minutes avant le début.', TRUE);