INSERT INTO product (
    id, name, description, price, stock_quantity, active
) VALUES
(1, 'Tapis de yoga', 'Tapis antidérapant pour les séances de yoga et de relaxation.', 25.00, 45, TRUE),
(2, 'Gourde isotherme', 'Gourde réutilisable pour les activités sportives et les sorties.', 40.00, 30, TRUE),
(3, 'Bande élastique de fitness', 'Bande de résistance pour les exercices de renforcement.', 18.00, 80, TRUE),
(4, 'Kit de badminton', 'Deux raquettes et des volants pour les loisirs en extérieur.', 32.00, 25, TRUE),
(5, 'Sac de randonnée', 'Sac léger avec plusieurs compartiments pour les sorties.', 55.00, 20, TRUE),
(6, 'Ballon de fitness', 'Ballon adapté aux exercices de mobilité et de renforcement.', 24.00, 35, TRUE),
(7, 'Casque de vélo', 'Casque réglable pour les balades à vélo.', 60.00, 22, TRUE),
(8, 'Serviette de sport', 'Serviette compacte et absorbante pour les activités sportives.', 16.00, 70, TRUE),
(9, 'Set de tennis de table', 'Deux raquettes et trois balles pour jouer au tennis de table.', 44.00, 28, TRUE),
(10, 'Corde à sauter', 'Corde réglable pour les entraînements cardio.', 30.00, 55, TRUE),
(11, 'Bloc de yoga', 'Bloc en mousse pour améliorer les postures de yoga.', 12.00, 65, TRUE),
(12, 'Sangle de yoga', 'Sangle réglable pour faciliter les étirements.', 14.00, 60, TRUE),
(13, 'Coussin de méditation', 'Coussin confortable pour les séances de méditation.', 38.00, 24, TRUE),
(14, 'Brassard de course', 'Brassard réglable pour transporter un téléphone pendant la course.', 20.00, 45, TRUE),
(15, 'Ceinture de running', 'Ceinture légère avec poche pour les sorties sportives.', 22.00, 40, TRUE),
(16, 'Lampe frontale', 'Lampe rechargeable pour les randonnées et sorties en soirée.', 35.00, 33, TRUE),
(17, 'Bâtons de randonnée', 'Paire de bâtons télescopiques pour les parcours en extérieur.', 48.00, 18, TRUE),
(18, 'Poncho de pluie', 'Poncho léger pour les activités extérieures par temps humide.', 19.00, 52, TRUE),
(19, 'Sac étanche', 'Sac imperméable pour protéger les effets personnels.', 27.00, 32, TRUE),
(20, 'Couverture de pique-nique', 'Couverture pliable pour les sorties et activités en plein air.', 29.00, 30, TRUE),
(21, 'Mini pompe à vélo', 'Pompe compacte pour les sorties à vélo.', 17.00, 50, TRUE),
(22, 'Antivol de vélo', 'Antivol pratique pour sécuriser un vélo.', 26.00, 42, TRUE),
(23, 'Gants de vélo', 'Gants confortables pour les balades et entraînements à vélo.', 21.00, 38, TRUE),
(24, 'Lunettes de sport', 'Lunettes adaptées aux activités extérieures.', 34.00, 36, TRUE),
(25, 'Maillot réfléchissant', 'Maillot visible pour les sorties sportives en extérieur.', 31.00, 27, TRUE),
(26, 'Sac à dos enfant', 'Petit sac pratique pour les stages et activités des enfants.', 28.00, 25, TRUE),
(27, 'Kit de dessin', 'Crayons, feutres et accessoires pour les ateliers créatifs.', 23.00, 44, TRUE),
(28, 'Carnet de croquis', 'Carnet à pages épaisses pour le dessin et la peinture.', 11.00, 75, TRUE),
(29, 'Set de pinceaux', 'Lot de pinceaux pour les activités artistiques.', 15.00, 58, TRUE),
(30, 'Tablier créatif', 'Tablier lavable pour les ateliers peinture et bricolage.', 18.00, 46, TRUE),
(31, 'Kit de poterie débutant', 'Petit kit d’outils pour découvrir la poterie.', 36.00, 26, TRUE),
(32, 'Argile autodurcissante', 'Argile facile à utiliser pour les créations manuelles.', 13.00, 62, TRUE),
(33, 'Peinture acrylique', 'Lot de peintures pour les ateliers artistiques.', 24.00, 48, TRUE),
(34, 'Puzzle 1000 pièces', 'Puzzle illustré pour les moments de détente.', 19.00, 39, TRUE),
(35, 'Jeu de cartes', 'Jeu de cartes classique pour les loisirs en groupe.', 9.00, 90, TRUE),
(36, 'Jeu de société familial', 'Jeu accessible pour partager un moment en famille.', 33.00, 34, TRUE),
(37, 'Carnet d’énigmes', 'Recueil d’énigmes pour les amateurs d’escape games.', 12.00, 54, TRUE),
(38, 'Kit d’échecs', 'Jeu d’échecs compact avec plateau pliable.', 27.00, 29, TRUE),
(39, 'Jeu de pétanque', 'Set de boules pour les loisirs en extérieur.', 42.00, 21, TRUE),
(40, 'Frisbee', 'Disque léger pour les activités en extérieur.', 10.00, 72, TRUE),
(41, 'Ballon de football', 'Ballon polyvalent pour les activités sportives.', 28.00, 47, TRUE),
(42, 'Ballon de basketball', 'Ballon adapté à la pratique du basketball.', 29.00, 41, TRUE),
(43, 'Ballon de volleyball', 'Ballon léger pour les activités de volleyball.', 26.00, 38, TRUE),
(44, 'Raquette de tennis', 'Raquette pour les loisirs et entraînements débutants.', 49.00, 22, TRUE),
(45, 'Boîte de balles de tennis', 'Lot de trois balles pour la pratique du tennis.', 11.00, 66, TRUE),
(46, 'Raquette de padel', 'Raquette adaptée à l’initiation au padel.', 58.00, 20, TRUE),
(47, 'Set de volants', 'Lot de volants pour les parties de badminton.', 8.00, 85, TRUE),
(48, 'Filet multisport', 'Filet facile à installer pour plusieurs jeux de plein air.', 45.00, 17, TRUE),
(49, 'Tapis de sol', 'Tapis pliable pour les exercices et activités extérieures.', 22.00, 36, TRUE),
(50, 'Haltères légers', 'Paire d’haltères pour les exercices de renforcement.', 30.00, 32, TRUE),
(51, 'Disque d’équilibre', 'Accessoire pour travailler l’équilibre et la mobilité.', 25.00, 28, TRUE),
(52, 'Rouleau de massage', 'Rouleau pour la récupération après une activité sportive.', 21.00, 43, TRUE),
(53, 'Élastiques de résistance', 'Lot de bandes de résistance de plusieurs niveaux.', 24.00, 51, TRUE),
(54, 'Step de fitness', 'Plateforme pour les séances de fitness et de cardio.', 39.00, 19, TRUE),
(55, 'Tapis de pilates', 'Tapis confortable pour les exercices au sol.', 27.00, 37, TRUE),
(56, 'Anneau de pilates', 'Anneau léger pour les exercices de tonification.', 18.00, 40, TRUE),
(57, 'Bouteille souple', 'Bouteille compacte pour les activités de plein air.', 14.00, 61, TRUE),
(58, 'Mousqueton porte-clés', 'Petit mousqueton pratique pour accrocher des accessoires.', 7.00, 95, TRUE),
(59, 'Boussole', 'Boussole simple pour les randonnées et jeux d’orientation.', 16.00, 56, TRUE),
(60, 'Carte étanche', 'Pochette étanche pour protéger une carte ou un document.', 13.00, 49, TRUE),
(61, 'Sac banane outdoor', 'Sac compact pour garder les petits objets accessibles.', 20.00, 44, TRUE),
(62, 'Chapeau de randonnée', 'Chapeau léger pour les sorties en extérieur.', 23.00, 31, TRUE),
(63, 'Gants de randonnée', 'Gants confortables pour les promenades par temps frais.', 18.00, 35, TRUE),
(64, 'Chaussettes de marche', 'Paire de chaussettes adaptées aux longues promenades.', 12.00, 74, TRUE),
(65, 'Boîte repas réutilisable', 'Boîte pratique pour les ateliers cuisine et sorties.', 17.00, 52, TRUE),
(66, 'Tablier de cuisine', 'Tablier lavable pour les ateliers culinaires.', 22.00, 43, TRUE),
(67, 'Manique de cuisine', 'Paire de maniques pour manipuler les plats chauds.', 10.00, 68, TRUE),
(68, 'Carnet de recettes', 'Carnet pour noter les recettes apprises en atelier.', 15.00, 57, TRUE),
(69, 'Moule à pâtisserie', 'Moule simple pour préparer des desserts à la maison.', 19.00, 36, TRUE),
(70, 'Spatule en silicone', 'Ustensile pratique pour les préparations culinaires.', 8.00, 83, TRUE),
(71, 'Kit pâtisserie enfant', 'Accessoires adaptés aux ateliers culinaires pour enfants.', 26.00, 28, TRUE),
(72, 'Casquette de sport', 'Casquette légère pour les activités extérieures.', 18.00, 49, TRUE),
(73, 'Sac de gym', 'Sac pratique pour transporter une tenue de sport.', 37.00, 33, TRUE),
(74, 'Bracelet réfléchissant', 'Bracelet visible pour les sorties à pied ou à vélo.', 9.00, 88, TRUE),
(75, 'Chasuble de sport', 'Chasuble légère pour les jeux en équipe.', 7.00, 92, TRUE),
(76, 'Sifflet d’arbitre', 'Sifflet simple pour encadrer les jeux sportifs.', 6.00, 100, TRUE),
(77, 'Cône d’entraînement', 'Lot de cônes pour organiser des exercices sportifs.', 18.00, 53, TRUE),
(78, 'Échelle d’agilité', 'Accessoire pour les entraînements de coordination.', 32.00, 24, TRUE),
(79, 'Protège-poignets', 'Protections pour le skateboard et les activités similaires.', 20.00, 34, TRUE),
(80, 'Genouillères', 'Paire de protections pour les activités sportives.', 25.00, 31, TRUE),
(81, 'Coudières', 'Paire de protections légères pour les loisirs sportifs.', 19.00, 37, TRUE),
(82, 'Planche d’équilibre', 'Planche pour les exercices de coordination et de stabilité.', 46.00, 18, TRUE),
(83, 'Sac pour raquettes', 'Sac adapté au transport du matériel de sports de raquette.', 35.00, 25, TRUE),
(84, 'Grip de raquette', 'Lot de grips pour améliorer la prise en main d’une raquette.', 9.00, 76, TRUE),
(85, 'Balles de ping-pong', 'Lot de balles pour le tennis de table.', 7.00, 94, TRUE),
(86, 'Filet de ping-pong', 'Filet amovible pour jouer au tennis de table.', 16.00, 45, TRUE),
(87, 'Kit de jonglage', 'Balles et accessoires pour découvrir la jonglerie.', 21.00, 36, TRUE),
(88, 'Cerceau', 'Cerceau léger pour les activités sportives et ludiques.', 12.00, 63, TRUE),
(89, 'Ruban de danse', 'Ruban coloré pour les ateliers de danse et de mouvement.', 10.00, 69, TRUE),
(90, 'Sac de natation', 'Sac pratique pour transporter les affaires de piscine.', 24.00, 39, TRUE),
(91, 'Bonnet de natation', 'Bonnet confortable pour les activités aquatiques.', 9.00, 82, TRUE),
(92, 'Lunettes de natation', 'Lunettes réglables pour la natation.', 17.00, 58, TRUE),
(93, 'Serviette microfibre', 'Serviette légère et compacte pour les activités aquatiques.', 15.00, 64, TRUE),
(94, 'Pochette imperméable', 'Pochette résistante à l’eau pour protéger de petits objets.', 12.00, 71, TRUE),
(95, 'Carnet de voyage', 'Carnet pour noter les souvenirs de sorties et découvertes.', 14.00, 60, TRUE),
(96, 'Appareil photo jetable', 'Appareil simple pour les promenades photographiques.', 18.00, 42, TRUE),
(97, 'Album photo', 'Album pour conserver les souvenirs des activités.', 20.00, 47, TRUE),
(98, 'Gilet de sécurité', 'Gilet visible pour les sorties de groupe en extérieur.', 11.00, 73, TRUE),
(99, 'Sac pliable', 'Sac léger et réutilisable pour transporter de petits achats.', 13.00, 79, TRUE),
(100, 'Porte-bidon de vélo', 'Support simple pour fixer une gourde sur un vélo.', 16.00, 55, TRUE);